ndnSIM QoS: nfd::fw::asf::RttStats Class Reference
nfd::fw::asf::RttStats Class Reference
#include <asf-measurements.hpp>
Public Types
typedef time::duration< double, boost::micro > Rtt
Public Member Functions
RttStats ()
void addRttMeasurement (RttEstimator::Duration &durationRtt)
void recordTimeout ()
Rtt getRtt () const
Rtt getSrtt () const
RttEstimator::Duration computeRto () const
Static Public Attributes
static const Rtt RTT_TIMEOUT
static const Rtt RTT_NO_MEASUREMENT
Detailed Description
Definition at line 37 of file asf-measurements.hpp.
Member Typedef Documentation
Rtt
typedef time::duration<double, boost::micro> nfd::fw::asf::RttStats::Rtt
Definition at line 40 of file asf-measurements.hpp.
Constructor & Destructor Documentation
RttStats()
nfd::fw::asf::RttStats::RttStats ()
Definition at line 38 of file asf-measurements.cpp.
Member Function Documentation
addRttMeasurement()
void nfd::fw::asf::RttStats::addRttMeasurement (RttEstimator::Duration & durationRtt)
Definition at line 45 of file asf-measurements.cpp.
Referenced by nfd::fw::asf::FaceInfo::recordRtt().
recordTimeout()
void nfd::fw::asf::RttStats::recordTimeout () inline
Definition at line 48 of file asf-measurements.hpp.
References RTT_TIMEOUT.
Referenced by nfd::fw::asf::FaceInfo::recordTimeout().
getRtt()
Rtt nfd::fw::asf::RttStats::getRtt () const inline
Definition at line 54 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::FaceInfo::getRtt(), and nfd::fw::asf::FaceInfo::recordRtt().
getSrtt()
Rtt nfd::fw::asf::RttStats::getSrtt () const inline
Definition at line 60 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::FaceInfo::getSrtt(), and nfd::fw::asf::FaceInfo::recordRtt().
computeRto()
RttEstimator::Duration nfd::fw::asf::RttStats::computeRto () const inline
Definition at line 66 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::FaceInfo::computeRto().
Member Data Documentation
RTT_TIMEOUT
const RttStats::Rtt nfd::fw::asf::RttStats::RTT_TIMEOUT static
Definition at line 76 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::getValueForSorting(), nfd::fw::asf::FaceInfo::isTimeout(), and recordTimeout().
RTT_NO_MEASUREMENT
const RttStats::Rtt nfd::fw::asf::RttStats::RTT_NO_MEASUREMENT static
Definition at line 77 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::getValueForSorting(), and nfd::fw::asf::FaceInfo::hasSrttMeasurement().
The documentation for this class was generated from the following files:
ndnSIM/NFD/daemon/fw/asf-measurements.hpp
ndnSIM/NFD/daemon/fw/asf-measurements.cpp