ndnSIM QoS: nfd::fw::asf::NamespaceInfo Class Reference
nfd::fw::asf::NamespaceInfo Class Reference
stores stategy information about each face in this namespace
#include <asf-measurements.hpp>
Public Member Functions
NamespaceInfo ()
FaceInfo & getOrCreateFaceInfo (const fib::Entry &fibEntry, FaceId faceId)
FaceInfo * getFaceInfo (const fib::Entry &fibEntry, FaceId faceId)
void expireFaceInfo (FaceId faceId)
void extendFaceInfoLifetime (FaceInfo &info, FaceId faceId)
FaceInfo * get (FaceId faceId)
FaceInfoTable::iterator find (FaceId faceId)
FaceInfoTable::iterator end ()
const FaceInfoTable::iterator insert (FaceId faceId)
bool isProbingDue () const
void setIsProbingDue (bool isProbingDue)
bool isFirstProbeScheduled () const
void setHasFirstProbeBeenScheduled (bool hasBeenScheduled)
Public Member Functions inherited from nfd::fw::StrategyInfo
virtual ~StrategyInfo ()=default
Static Public Member Functions
static constexpr int getTypeId ()
Static Public Member Functions inherited from nfd::fw::StrategyInfo
static constexpr int getTypeId ()
Additional Inherited Members
Protected Member Functions inherited from nfd::fw::StrategyInfo
StrategyInfo ()=default
Detailed Description
stores stategy information about each face in this namespace
Definition at line 208 of file asf-measurements.hpp.
Constructor & Destructor Documentation
NamespaceInfo()
nfd::fw::asf::NamespaceInfo::NamespaceInfo ()
Definition at line 144 of file asf-measurements.cpp.
Member Function Documentation
getTypeId()
static constexpr int nfd::fw::asf::NamespaceInfo::getTypeId () inline static constexpr
Definition at line 214 of file asf-measurements.hpp.
getOrCreateFaceInfo()
FaceInfo & nfd::fw::asf::NamespaceInfo::getOrCreateFaceInfo (const fib::Entry & fibEntry, FaceId faceId)
Definition at line 164 of file asf-measurements.cpp.
References extendFaceInfoLifetime().
Referenced by nfd::fw::asf::AsfMeasurements::getOrCreateFaceInfo().
getFaceInfo()
FaceInfo * nfd::fw::asf::NamespaceInfo::getFaceInfo (const fib::Entry & fibEntry, FaceId faceId)
Definition at line 151 of file asf-measurements.cpp.
Referenced by nfd::fw::asf::AsfMeasurements::getFaceInfo().
expireFaceInfo()
void nfd::fw::asf::NamespaceInfo::expireFaceInfo (FaceId faceId)
Definition at line 184 of file asf-measurements.cpp.
Referenced by extendFaceInfoLifetime().
extendFaceInfoLifetime()
void nfd::fw::asf::NamespaceInfo::extendFaceInfoLifetime (FaceInfo & info, FaceId faceId)
Definition at line 190 of file asf-measurements.cpp.
References expireFaceInfo(), nfd::fw::asf::FaceInfo::getMeasurementExpirationEventId(), nfd::fw::asf::AsfMeasurements::MEASUREMENTS_LIFETIME, and nfd::fw::asf::FaceInfo::setMeasurementExpirationEventId().
Referenced by nfd::fw::asf::AsfStrategy::beforeSatisfyInterest(), and getOrCreateFaceInfo().
get()
FaceInfo* nfd::fw::asf::NamespaceInfo::get (FaceId faceId) inline
Definition at line 232 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::AsfStrategy::beforeSatisfyInterest().
find()
FaceInfoTable::iterator nfd::fw::asf::NamespaceInfo::find (FaceId faceId) inline
Definition at line 243 of file asf-measurements.hpp.
end()
FaceInfoTable::iterator nfd::fw::asf::NamespaceInfo::end () inline
Definition at line 249 of file asf-measurements.hpp.
insert()
const FaceInfoTable::iterator nfd::fw::asf::NamespaceInfo::insert (FaceId faceId) inline
Definition at line 255 of file asf-measurements.hpp.
isProbingDue()
bool nfd::fw::asf::NamespaceInfo::isProbingDue () const inline
Definition at line 261 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::ProbingModule::isProbingNeeded(), and setIsProbingDue().
setIsProbingDue()
void nfd::fw::asf::NamespaceInfo::setIsProbingDue (bool isProbingDue) inline
Definition at line 267 of file asf-measurements.hpp.
References isProbingDue().
Referenced by nfd::fw::asf::ProbingModule::afterForwardingProbe(), and nfd::fw::asf::ProbingModule::scheduleProbe().
isFirstProbeScheduled()
bool nfd::fw::asf::NamespaceInfo::isFirstProbeScheduled () const inline
Definition at line 273 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::ProbingModule::isProbingNeeded().
setHasFirstProbeBeenScheduled()
void nfd::fw::asf::NamespaceInfo::setHasFirstProbeBeenScheduled (bool hasBeenScheduled) inline
Definition at line 279 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::ProbingModule::isProbingNeeded().
The documentation for this class was generated from the following files:
ndnSIM/NFD/daemon/fw/asf-measurements.hpp
ndnSIM/NFD/daemon/fw/asf-measurements.cpp