ndnSIM QoS: nfd::fw::ProcessNackTraitsBase Class Reference
nfd::fw::ProcessNackTraitsBase Class Reference abstract
provides a common procedure for processing Nacks
#include <process-nack-traits.hpp>
Protected Member Functions
virtual ~ProcessNackTraitsBase ()=default
void processNack (const Face &inFace, const lp::Nack &nack, const shared_ptr< pit::Entry > &pitEntry)
Detailed Description
provides a common procedure for processing Nacks
This procedure works as follows:
If Nacks have been received from all upstream faces, return a Nack with least severe reason to downstream faces.
If there are more than one upstream face, Nacks have been received from all but one of them, and that face is also a downstream, return a Nack to that face. This is to address a specific "live deadlock" scenario where two hosts are waiting for each other to return the Nack.
Otherwise, wait for the arrival of more Nacks or Data.
To use this helper, the strategy should inherit from ProcessNackTraits<MyStrategy>, and declare that specialization as a friend class. Then, invoke processNack from afterReceiveNack trigger.
Definition at line 49 of file process-nack-traits.hpp.
Constructor & Destructor Documentation
~ProcessNackTraitsBase()
virtual nfd::fw::ProcessNackTraitsBase::~ProcessNackTraitsBase () protected virtual default
Member Function Documentation
processNack()
void nfd::fw::ProcessNackTraitsBase::processNack (const Face & inFace, const lp::Nack & nack, const shared_ptr< pit::Entry > & pitEntry) protected
Definition at line 35 of file process-nack-traits.cpp.
Referenced by nfd::fw::BestRouteStrategy2::afterReceiveNack(), nfd::fw::MulticastStrategy::afterReceiveNack(), nfd::fw::QosStrategy::afterReceiveNack(), and nfd::fw::QosStrategy::prioritySendNack().
The documentation for this class was generated from the following files:
ndnSIM/NFD/daemon/fw/process-nack-traits.hpp
ndnSIM/NFD/daemon/fw/process-nack-traits.cpp