ndnSIM QoS: nfd::fw::NccStrategy::MeasurementsEntryInfo Class Reference
nfd::fw::NccStrategy::MeasurementsEntryInfo Class Reference
StrategyInfo on measurements::Entry.
#include <ncc-strategy.hpp>
Public Member Functions
MeasurementsEntryInfo ()
void inheritFrom (const MeasurementsEntryInfo &other)
shared_ptr< Face > getBestFace ()
void updateBestFace (const Face &face)
void adjustPredictUp ()
Public Member Functions inherited from nfd::fw::StrategyInfo
virtual ~StrategyInfo ()=default
Static Public Member Functions
static constexpr int getTypeId ()
Static Public Member Functions inherited from nfd::fw::StrategyInfo
static constexpr int getTypeId ()
Public Attributes
weak_ptr< Face > bestFace
weak_ptr< Face > previousFace
time::microseconds prediction
Static Public Attributes
static const time::microseconds INITIAL_PREDICTION = 8192_us
static const time::microseconds MIN_PREDICTION = 127_us
static const int ADJUST_PREDICT_DOWN_SHIFT = 7
static const time::microseconds MAX_PREDICTION = 160_ms
static const int ADJUST_PREDICT_UP_SHIFT = 3
Additional Inherited Members
Protected Member Functions inherited from nfd::fw::StrategyInfo
StrategyInfo ()=default
Detailed Description
StrategyInfo on measurements::Entry.
Definition at line 55 of file ncc-strategy.hpp.
Constructor & Destructor Documentation
MeasurementsEntryInfo()
nfd::fw::NccStrategy::MeasurementsEntryInfo::MeasurementsEntryInfo ()
Definition at line 277 of file ncc-strategy.cpp.
Member Function Documentation
getTypeId()
static constexpr int nfd::fw::NccStrategy::MeasurementsEntryInfo::getTypeId () inline static constexpr
Definition at line 59 of file ncc-strategy.hpp.
inheritFrom()
void nfd::fw::NccStrategy::MeasurementsEntryInfo::inheritFrom (const MeasurementsEntryInfo & other)
Definition at line 283 of file ncc-strategy.cpp.
Referenced by nfd::fw::NccStrategy::getMeasurementsEntryInfo().
getBestFace()
shared_ptr< Face > nfd::fw::NccStrategy::MeasurementsEntryInfo::getBestFace ()
Definition at line 289 of file ncc-strategy.cpp.
Referenced by nfd::fw::NccStrategy::afterReceiveInterest(), and nfd::fw::NccStrategy::beforeSatisfyInterest().
updateBestFace()
void nfd::fw::NccStrategy::MeasurementsEntryInfo::updateBestFace (const Face & face)
Definition at line 300 of file ncc-strategy.cpp.
Referenced by nfd::fw::NccStrategy::beforeSatisfyInterest().
adjustPredictUp()
void nfd::fw::NccStrategy::MeasurementsEntryInfo::adjustPredictUp ()
Definition at line 324 of file ncc-strategy.cpp.
Referenced by nfd::fw::NccStrategy::timeoutOnBestFace().
Member Data Documentation
bestFace
weak_ptr<Face> nfd::fw::NccStrategy::MeasurementsEntryInfo::bestFace
Definition at line 86 of file ncc-strategy.hpp.
previousFace
weak_ptr<Face> nfd::fw::NccStrategy::MeasurementsEntryInfo::previousFace
Definition at line 87 of file ncc-strategy.hpp.
Referenced by nfd::fw::NccStrategy::afterReceiveInterest(), and nfd::fw::NccStrategy::doPropagate().
prediction
time::microseconds nfd::fw::NccStrategy::MeasurementsEntryInfo::prediction
Definition at line 88 of file ncc-strategy.hpp.
Referenced by nfd::fw::NccStrategy::afterReceiveInterest().
INITIAL_PREDICTION
const time::microseconds nfd::fw::NccStrategy::MeasurementsEntryInfo::INITIAL_PREDICTION = 8192_us static
Definition at line 90 of file ncc-strategy.hpp.
MIN_PREDICTION
const time::microseconds nfd::fw::NccStrategy::MeasurementsEntryInfo::MIN_PREDICTION = 127_us static
Definition at line 91 of file ncc-strategy.hpp.
ADJUST_PREDICT_DOWN_SHIFT
const int nfd::fw::NccStrategy::MeasurementsEntryInfo::ADJUST_PREDICT_DOWN_SHIFT = 7 static
Definition at line 92 of file ncc-strategy.hpp.
MAX_PREDICTION
const time::microseconds nfd::fw::NccStrategy::MeasurementsEntryInfo::MAX_PREDICTION = 160_ms static
Definition at line 93 of file ncc-strategy.hpp.
ADJUST_PREDICT_UP_SHIFT
const int nfd::fw::NccStrategy::MeasurementsEntryInfo::ADJUST_PREDICT_UP_SHIFT = 3 static
Definition at line 94 of file ncc-strategy.hpp.
The documentation for this class was generated from the following files:
ndnSIM/NFD/daemon/fw/ncc-strategy.hpp
ndnSIM/NFD/daemon/fw/ncc-strategy.cpp