ndnSIM QoS: ns3::ndn::TBDriver Class Reference
ns3::ndn::TBDriver Class Reference
App meant to define and drive token generation for traffic control.
#include <tokenBucketDriver.hpp>
Public Member Functions
TBDriver ()
void ScheduleNextToken (int bucket)
Schedule the next instance of token generation for the indicated bucket.
void UpdateBucket (int bucket)
Sends command to indicated token bucket to generate a new token.
Public Member Functions inherited from ns3::ndn::App
App ()
Default constructor.
virtual ~App ()
uint32_t GetId () const
Get application ID (ID of applications face)
virtual void OnInterest (shared_ptr< const Interest > interest)
Method that will be called every time new Interest arrives.
virtual void OnData (shared_ptr< const Data > data)
Method that will be called every time new Data arrives.
virtual void OnNack (shared_ptr< const lp::Nack > nack)
Method that will be called every time new Nack arrives.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::ndn::App
static TypeId GetTypeId ()
Protected Member Functions
virtual void StartApplication ()
Called at time specified by Start.
virtual void StopApplication ()
Called at time specified by Stop.
Protected Member Functions inherited from ns3::ndn::App
virtual void DoInitialize ()
virtual void DoDispose ()
Protected Attributes
EventId m_sendEvent
EventId of pending "send packet" event.
Protected Attributes inherited from ns3::ndn::App
bool m_active
Flag to indicate that application is active (set by StartApplication and StopApplication)
shared_ptr< Face > m_face
AppLinkService * m_appLink
uint32_t m_appId
TracedCallback< shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face > > m_receivedInterests
App-level trace of received Interests.
TracedCallback< shared_ptr< const Data >, Ptr< App >, shared_ptr< Face > > m_receivedDatas
App-level trace of received Data.
TracedCallback< shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face > > m_receivedNacks
App-level trace of received Nacks.
TracedCallback< shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face > > m_transmittedInterests
App-level trace of transmitted Interests.
TracedCallback< shared_ptr< const Data >, Ptr< App >, shared_ptr< Face > > m_transmittedDatas
App-level trace of transmitted Data.
TracedCallback< shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face > > m_transmittedNacks
App-level trace of transmitted Nacks.
Additional Inherited Members
Public Types inherited from ns3::ndn::App
typedef void(* InterestTraceCallback) (shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face >)
typedef void(* DataTraceCallback) (shared_ptr< const Data >, Ptr< App >, shared_ptr< Face >)
typedef void(* NackTraceCallback) (shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face >)
Detailed Description
App meant to define and drive token generation for traffic control.
Defines token bucket capacity, and generation rate for strategy level token bucket objects; one for each of the priority queues. Also sends token generation commands to token bucket at the given generation rate.
Uses references provided by TBucketRef class in order to communicate with the token buckets that reside at the strategy level.
Definition at line 47 of file tokenBucketDriver.hpp.
Constructor & Destructor Documentation
TBDriver()
ns3::ndn::TBDriver::TBDriver ()
Definition at line 71 of file tokenBucketDriver.cpp.
Member Function Documentation
GetTypeId()
TypeId ns3::ndn::TBDriver::GetTypeId (void) static
Definition at line 48 of file tokenBucketDriver.cpp.
ScheduleNextToken()
void ns3::ndn::TBDriver::ScheduleNextToken (int bucket)
Schedule the next instance of token generation for the indicated bucket.
Parameters
bucket The token bucket that we are scheduling for.
Definition at line 100 of file tokenBucketDriver.cpp.
References m_sendEvent, and UpdateBucket().
Referenced by StartApplication(), and UpdateBucket().
UpdateBucket()
void ns3::ndn::TBDriver::UpdateBucket (int bucket)
Sends command to indicated token bucket to generate a new token.
Parameters
bucket The token bucket that we are sending the token generation command to.
Definition at line 127 of file tokenBucketDriver.cpp.
References nfd::fw::TokenBucket::addToken(), nfd::fw::CT, nfd::fw::TokenBucket::m_capacity, ScheduleNextToken(), nfd::fw::TBRef::sender1, nfd::fw::TBRef::sender2, and nfd::fw::TBRef::sender3.
Referenced by ScheduleNextToken().
StartApplication()
void ns3::ndn::TBDriver::StartApplication () protected virtual
Called at time specified by Start.
Reimplemented from ns3::ndn::App.
Definition at line 82 of file tokenBucketDriver.cpp.
References ScheduleNextToken(), and ns3::ndn::App::StartApplication().
StopApplication()
void ns3::ndn::TBDriver::StopApplication () protected virtual
Called at time specified by Stop.
Reimplemented from ns3::ndn::App.
Definition at line 93 of file tokenBucketDriver.cpp.
References ns3::ndn::App::StopApplication().
Member Data Documentation
m_sendEvent
EventId ns3::ndn::TBDriver::m_sendEvent protected
EventId of pending "send packet" event.
Definition at line 70 of file tokenBucketDriver.hpp.
Referenced by ScheduleNextToken().
The documentation for this class was generated from the following files:
ndnSIM/apps/tokenBucketDriver.hpp
ndnSIM/apps/tokenBucketDriver.cpp