ndnSIM QoS: nfd::fw::NdnPriorityTxQueue Class Reference
nfd::fw::NdnPriorityTxQueue Class Reference
Class defines priority queue.
#include <ndn-priority-tx-queue.hpp>
Public Member Functions
NdnPriorityTxQueue ()
float GetFlowRate (QosQueue *queue)
Find flow rate of the given queue.
void UpdateTime (ndn::Block packet, QosQueue *queue)
Update the time of the given packet within the queue.
int SelectQueueToSend (double highTokens, double midTokens, double lowTokens)
Use WFQ algorithm to select the next queue to send from taking the token count into account.
bool DoEnqueue (QueueItem item, uint32_t pr_level)
Push the given packet and corresponding meta info onto a queue.
QueueItem DoDequeue (int choice)
Dequeue a packet from the indicated queue.
bool IsEmpty ()
Check if all queues are empty.
int tokenReqHig ()
Tokens required for high priority queue.
int tokenReqMid ()
Tokens required for medium priority queue.
int tokenReqLow ()
Tokens required for low priority queue.
Public Attributes
QosQueue m_highPriorityQueue
QosQueue m_mediumPriorityQueue
QosQueue m_lowPriorityQueue
Detailed Description
Class defines priority queue.
Consists of three QoS queues each with different priority levels. Makes use of Weighted Fair Queuing algrothrim to process queues.
Definition at line 51 of file ndn-priority-tx-queue.hpp.
Constructor & Destructor Documentation
NdnPriorityTxQueue()
nfd::fw::NdnPriorityTxQueue::NdnPriorityTxQueue ()
Definition at line 30 of file ndn-priority-tx-queue.cpp.
References m_highPriorityQueue, m_lowPriorityQueue, m_mediumPriorityQueue, and nfd::fw::QosQueue::SetWeight().
Member Function Documentation
GetFlowRate()
float nfd::fw::NdnPriorityTxQueue::GetFlowRate (QosQueue * queue)
Find flow rate of the given queue.
Parameters
queue The queue form which we will obtain the flow rate.
Definition at line 38 of file ndn-priority-tx-queue.cpp.
References nfd::fw::QosQueue::GetWeight(), m_highPriorityQueue, m_lowPriorityQueue, and m_mediumPriorityQueue.
Referenced by UpdateTime().
UpdateTime()
void nfd::fw::NdnPriorityTxQueue::UpdateTime (ndn::Block packet, QosQueue * queue)
Update the time of the given packet within the queue.
Parameters
packet The packet we are updating.
queue The queue which has the packet we want to update.
Definition at line 47 of file ndn-priority-tx-queue.cpp.
References GetFlowRate(), nfd::fw::QosQueue::GetLastVirtualFinishTime(), and nfd::fw::QosQueue::SetLastVirtualFinishTime().
Referenced by DoEnqueue().
SelectQueueToSend()
int nfd::fw::NdnPriorityTxQueue::SelectQueueToSend (double highTokens, double midTokens, double lowTokens)
Use WFQ algorithm to select the next queue to send from taking the token count into account.
Parameters
highTokens The number of tokens the high priorty queue has.
midTokens The number of tokens the mid priorty queue has.
lowTokens The number of tokens the low priorty queue has.
Definition at line 57 of file ndn-priority-tx-queue.cpp.
References nfd::fw::QosQueue::GetLastVirtualFinishTime(), nfd::fw::QosQueue::IsEmpty(), m_highPriorityQueue, m_lowPriorityQueue, and m_mediumPriorityQueue.
DoEnqueue()
bool nfd::fw::NdnPriorityTxQueue::DoEnqueue (QueueItem item, uint32_t pr_level)
Push the given packet and corresponding meta info onto a queue.
Parameters
item The packet and its metainfo, incoming face, pit entry, etc.
pr_level The value which determins packet priorty.
Definition at line 92 of file ndn-priority-tx-queue.cpp.
References nfd::fw::QosQueue::Enqueue(), m_highPriorityQueue, m_lowPriorityQueue, m_mediumPriorityQueue, UpdateTime(), and nfd::fw::QueueItem::wireEncode.
DoDequeue()
QueueItem nfd::fw::NdnPriorityTxQueue::DoDequeue (int choice)
Dequeue a packet from the indicated queue.
Parameters
choice An int value repersenting one of the three queues.
Definition at line 115 of file ndn-priority-tx-queue.cpp.
References nfd::fw::QosQueue::Dequeue(), nfd::fw::QosQueue::IsEmpty(), m_highPriorityQueue, m_lowPriorityQueue, and m_mediumPriorityQueue.
IsEmpty()
bool nfd::fw::NdnPriorityTxQueue::IsEmpty ()
Check if all queues are empty.
Definition at line 135 of file ndn-priority-tx-queue.cpp.
References nfd::fw::QosQueue::IsEmpty(), m_highPriorityQueue, m_lowPriorityQueue, and m_mediumPriorityQueue.
tokenReqHig()
int nfd::fw::NdnPriorityTxQueue::tokenReqHig ()
Tokens required for high priority queue.
Definition at line 141 of file ndn-priority-tx-queue.cpp.
References nfd::fw::QosQueue::IsEmpty(), and m_highPriorityQueue.
tokenReqMid()
int nfd::fw::NdnPriorityTxQueue::tokenReqMid ()
Tokens required for medium priority queue.
Definition at line 151 of file ndn-priority-tx-queue.cpp.
References nfd::fw::QosQueue::IsEmpty(), and m_mediumPriorityQueue.
tokenReqLow()
int nfd::fw::NdnPriorityTxQueue::tokenReqLow ()
Tokens required for low priority queue.
Definition at line 161 of file ndn-priority-tx-queue.cpp.
References nfd::fw::QosQueue::IsEmpty(), and m_lowPriorityQueue.
Member Data Documentation
m_highPriorityQueue
QosQueue nfd::fw::NdnPriorityTxQueue::m_highPriorityQueue
Definition at line 115 of file ndn-priority-tx-queue.hpp.
Referenced by DoDequeue(), DoEnqueue(), GetFlowRate(), IsEmpty(), NdnPriorityTxQueue(), SelectQueueToSend(), and tokenReqHig().
m_mediumPriorityQueue
QosQueue nfd::fw::NdnPriorityTxQueue::m_mediumPriorityQueue
Definition at line 116 of file ndn-priority-tx-queue.hpp.
Referenced by DoDequeue(), DoEnqueue(), GetFlowRate(), IsEmpty(), NdnPriorityTxQueue(), SelectQueueToSend(), and tokenReqMid().
m_lowPriorityQueue
QosQueue nfd::fw::NdnPriorityTxQueue::m_lowPriorityQueue
Definition at line 117 of file ndn-priority-tx-queue.hpp.
Referenced by DoDequeue(), DoEnqueue(), GetFlowRate(), IsEmpty(), NdnPriorityTxQueue(), SelectQueueToSend(), and tokenReqLow().
The documentation for this class was generated from the following files:
ndnSIM/NFD/daemon/fw/ndn-priority-tx-queue.hpp
ndnSIM/NFD/daemon/fw/ndn-priority-tx-queue.cpp