ndnSIM QoS: ns3::ndn::TBucket Class Reference
ns3::ndn::TBucket Class Reference
NDN applications
A simple app meant to produce tokens Generates tokesn at a given frequency and updates the appropriate token buckets.
#include <token-bucket.hpp>
Public Member Functions
TBucket ()
void ScheduleNextToken (int bucket)
Schedule the next instance of token generation for the indicated bucket.
void UpdateBucket (int bucket)
Generate a new token for the indicated bucket.
Public Member Functions inherited from ns3::ndn::App
App ()
Default constructor.
virtual ~App ()
uint32_t GetId () const
Get application ID (ID of applications face)
virtual void OnInterest (shared_ptr< const Interest > interest)
Method that will be called every time new Interest arrives.
virtual void OnData (shared_ptr< const Data > data)
Method that will be called every time new Data arrives.
virtual void OnNack (shared_ptr< const lp::Nack > nack)
Method that will be called every time new Nack arrives.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::ndn::App
static TypeId GetTypeId ()
Protected Member Functions
virtual void StartApplication ()
Called at time specified by Start.
virtual void StopApplication ()
Called at time specified by Stop.
Protected Member Functions inherited from ns3::ndn::App
virtual void DoInitialize ()
virtual void DoDispose ()
Protected Attributes
EventId m_sendEvent
EventId of pending "send packet" event.
Protected Attributes inherited from ns3::ndn::App
bool m_active
Flag to indicate that application is active (set by StartApplication and StopApplication)
shared_ptr< Face > m_face
AppLinkService * m_appLink
uint32_t m_appId
TracedCallback< shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face > > m_receivedInterests
App-level trace of received Interests.
TracedCallback< shared_ptr< const Data >, Ptr< App >, shared_ptr< Face > > m_receivedDatas
App-level trace of received Data.
TracedCallback< shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face > > m_receivedNacks
App-level trace of received Nacks.
TracedCallback< shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face > > m_transmittedInterests
App-level trace of transmitted Interests.
TracedCallback< shared_ptr< const Data >, Ptr< App >, shared_ptr< Face > > m_transmittedDatas
App-level trace of transmitted Data.
TracedCallback< shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face > > m_transmittedNacks
App-level trace of transmitted Nacks.
Additional Inherited Members
Public Types inherited from ns3::ndn::App
typedef void(* InterestTraceCallback) (shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face >)
typedef void(* DataTraceCallback) (shared_ptr< const Data >, Ptr< App >, shared_ptr< Face >)
typedef void(* NackTraceCallback) (shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face >)
Detailed Description
A simple app meant to produce tokens Generates tokesn at a given frequency and updates the appropriate token buckets.
Definition at line 40 of file token-bucket.hpp.
Constructor & Destructor Documentation
TBucket()
ns3::ndn::TBucket::TBucket ()
Definition at line 69 of file token-bucket.cpp.
Member Function Documentation
GetTypeId()
TypeId ns3::ndn::TBucket::GetTypeId (void) static
Definition at line 46 of file token-bucket.cpp.
ScheduleNextToken()
void ns3::ndn::TBucket::ScheduleNextToken (int bucket)
Schedule the next instance of token generation for the indicated bucket.
Parameters
bucket the bucket we are scheduling token generation for.
Definition at line 98 of file token-bucket.cpp.
References m_sendEvent, and UpdateBucket().
Referenced by StartApplication(), and UpdateBucket().
UpdateBucket()
void ns3::ndn::TBucket::UpdateBucket (int bucket)
Generate a new token for the indicated bucket.
Parameters
bucket the bucket we are generating the token for.
Definition at line 125 of file token-bucket.cpp.
References nfd::fw::TokenBucket::addToken(), nfd::fw::CT, nfd::fw::TokenBucket::m_capacity, ScheduleNextToken(), nfd::fw::Consumed::sender1, nfd::fw::Consumed::sender2, and nfd::fw::Consumed::sender3.
Referenced by ScheduleNextToken().
StartApplication()
void ns3::ndn::TBucket::StartApplication () protected virtual
Called at time specified by Start.
Reimplemented from ns3::ndn::App.
Definition at line 80 of file token-bucket.cpp.
References ScheduleNextToken(), and ns3::ndn::App::StartApplication().
StopApplication()
void ns3::ndn::TBucket::StopApplication () protected virtual
Called at time specified by Stop.
Reimplemented from ns3::ndn::App.
Definition at line 91 of file token-bucket.cpp.
References ns3::ndn::App::StopApplication().
Member Data Documentation
m_sendEvent
EventId ns3::ndn::TBucket::m_sendEvent protected
EventId of pending "send packet" event.
Definition at line 63 of file token-bucket.hpp.
Referenced by ScheduleNextToken().
The documentation for this class was generated from the following files:
ndnSIM/apps/token-bucket.hpp
ndnSIM/apps/token-bucket.cpp