ndnSIM: ns3::ndn::App Class Reference
ns3::ndn::App Class Reference
NDN applications
Base class that all NDN applications should be derived from.
#include <ndn-app.hpp>
Public Types
typedef void(* InterestTraceCallback) (shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face >)
typedef void(* DataTraceCallback) (shared_ptr< const Data >, Ptr< App >, shared_ptr< Face >)
typedef void(* NackTraceCallback) (shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face >)
Public Member Functions
App ()
Default constructor.
virtual ~App ()
uint32_t GetId () const
Get application ID (ID of applications face)
virtual void OnInterest (shared_ptr< const Interest > interest)
Method that will be called every time new Interest arrives.
virtual void OnData (shared_ptr< const Data > data)
Method that will be called every time new Data arrives.
virtual void OnNack (shared_ptr< const lp::Nack > nack)
Method that will be called every time new Nack arrives.
Static Public Member Functions
static TypeId GetTypeId ()
Protected Member Functions
virtual void DoInitialize ()
virtual void DoDispose ()
virtual void StartApplication ()
Called at time specified by Start.
virtual void StopApplication ()
Called at time specified by Stop.
Protected Attributes
bool m_active
Flag to indicate that application is active (set by StartApplication and StopApplication)
shared_ptr< Face > m_face
AppLinkService * m_appLink
uint32_t m_appId
TracedCallback< shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face > > m_receivedInterests
App-level trace of received Interests.
TracedCallback< shared_ptr< const Data >, Ptr< App >, shared_ptr< Face > > m_receivedDatas
App-level trace of received Data.
TracedCallback< shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face > > m_receivedNacks
App-level trace of received Nacks.
TracedCallback< shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face > > m_transmittedInterests
App-level trace of transmitted Interests.
TracedCallback< shared_ptr< const Data >, Ptr< App >, shared_ptr< Face > > m_transmittedDatas
App-level trace of transmitted Data.
TracedCallback< shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face > > m_transmittedNacks
App-level trace of transmitted Nacks.
Detailed Description
Base class that all NDN applications should be derived from.
The class implements virtual calls onInterest, onNack, and onData
Definition at line 48 of file ndn-app.hpp.
Member Typedef Documentation
InterestTraceCallback
typedef void(* ns3::ndn::App::InterestTraceCallback) (shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face >)
Definition at line 84 of file ndn-app.hpp.
DataTraceCallback
typedef void(* ns3::ndn::App::DataTraceCallback) (shared_ptr< const Data >, Ptr< App >, shared_ptr< Face >)
Definition at line 85 of file ndn-app.hpp.
NackTraceCallback
typedef void(* ns3::ndn::App::NackTraceCallback) (shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face >)
Definition at line 86 of file ndn-app.hpp.
Constructor & Destructor Documentation
App()
ns3::ndn::App::App ()
Default constructor.
Definition at line 70 of file ndn-app.cpp.
~App()
ns3::ndn::App::~App () virtual
Definition at line 77 of file ndn-app.cpp.
Member Function Documentation
GetTypeId()
TypeId ns3::ndn::App::GetTypeId (void) static
Definition at line 37 of file ndn-app.cpp.
References m_receivedDatas, m_receivedInterests, m_receivedNacks, m_transmittedDatas, m_transmittedInterests, and m_transmittedNacks.
GetId()
uint32_t ns3::ndn::App::GetId () const
Get application ID (ID of applications face)
Definition at line 108 of file ndn-app.cpp.
References m_appId.
Referenced by ns3::ndn::Aggregator::OnData(), ns3::ndn::ConsumerQos::OnData(), ns3::ndn::Subscriber::OnData(), ns3::ndn::Aggregator::OnInterest(), ns3::ndn::SpontaneousProducer::OnInterest(), ns3::ndn::Producer::OnInterest(), ns3::ndn::Aggregator::SendAggInterest(), ns3::ndn::SpontaneousProducer::SendData(), ns3::ndn::Subscriber::SendPacket(), and ns3::ndn::ConsumerQos::SendPacket().
OnInterest()
void ns3::ndn::App::OnInterest (shared_ptr< const Interest > interest) virtual
Method that will be called every time new Interest arrives.
Reimplemented in ns3::ndn::Producer, ns3::ndn::SpontaneousProducer, and ns3::ndn::Aggregator.
Definition at line 114 of file ndn-app.cpp.
References m_face, and m_receivedInterests.
Referenced by ns3::ndn::Aggregator::OnInterest(), ns3::ndn::SpontaneousProducer::OnInterest(), and ns3::ndn::Producer::OnInterest().
OnData()
void ns3::ndn::App::OnData (shared_ptr< const Data > data) virtual
Method that will be called every time new Data arrives.
Reimplemented in ns3::ndn::ConsumerPcon, ns3::ndn::Subscriber, ns3::ndn::ConsumerQos, ns3::ndn::Consumer, ns3::ndn::ConsumerWindow, and ns3::ndn::Aggregator.
Definition at line 121 of file ndn-app.cpp.
References m_face, and m_receivedDatas.
Referenced by ns3::ndn::Aggregator::OnData(), ns3::ndn::Consumer::OnData(), ns3::ndn::ConsumerQos::OnData(), and ns3::ndn::Subscriber::OnData().
OnNack()
void ns3::ndn::App::OnNack (shared_ptr< const lp::Nack > nack) virtual
Method that will be called every time new Nack arrives.
Reimplemented in ns3::ndn::Consumer.
Definition at line 128 of file ndn-app.cpp.
References m_face, and m_receivedNacks.
Referenced by ns3::ndn::Consumer::OnNack().
DoInitialize()
void ns3::ndn::App::DoInitialize () protected virtual
Definition at line 82 of file ndn-app.cpp.
References m_appId.
DoDispose()
void ns3::ndn::App::DoDispose (void) protected virtual
Definition at line 97 of file ndn-app.cpp.
StartApplication()
void ns3::ndn::App::StartApplication () protected virtual
Called at time specified by Start.
Reimplemented in ns3::ndn::TBucket, ns3::ndn::Subscriber, ns3::ndn::ConsumerQos, ns3::ndn::Producer, ns3::ndn::SpontaneousProducer, ns3::ndn::Consumer, and ns3::ndn::Aggregator.
Definition at line 138 of file ndn-app.cpp.
References m_active, m_appLink, and m_face.
Referenced by ns3::ndn::Aggregator::StartApplication(), ns3::ndn::Consumer::StartApplication(), ns3::ndn::SpontaneousProducer::StartApplication(), ns3::ndn::Producer::StartApplication(), ns3::ndn::ConsumerQos::StartApplication(), ns3::ndn::Subscriber::StartApplication(), and ns3::ndn::TBucket::StartApplication().
StopApplication()
void ns3::ndn::App::StopApplication () protected virtual
Called at time specified by Stop.
Reimplemented in ns3::ndn::TBucket, ns3::ndn::Subscriber, ns3::ndn::ConsumerQos, ns3::ndn::Producer, ns3::ndn::SpontaneousProducer, ns3::ndn::Consumer, and ns3::ndn::Aggregator.
Definition at line 162 of file ndn-app.cpp.
References m_active, and m_face.
Referenced by ns3::ndn::Aggregator::StopApplication(), ns3::ndn::Consumer::StopApplication(), ns3::ndn::SpontaneousProducer::StopApplication(), ns3::ndn::Producer::StopApplication(), ns3::ndn::ConsumerQos::StopApplication(), ns3::ndn::Subscriber::StopApplication(), and ns3::ndn::TBucket::StopApplication().
Member Data Documentation
m_active
bool ns3::ndn::App::m_active protected
Flag to indicate that application is active (set by StartApplication and StopApplication)
Definition at line 103 of file ndn-app.hpp.
Referenced by ns3::ndn::Aggregator::OnData(), ns3::ndn::Consumer::OnData(), ns3::ndn::ConsumerQos::OnData(), ns3::ndn::Subscriber::OnData(), ns3::ndn::SpontaneousProducer::OnInterest(), ns3::ndn::Producer::OnInterest(), ns3::ndn::Aggregator::SendAggInterest(), ns3::ndn::SpontaneousProducer::SendData(), ns3::ndn::ConsumerZipfMandelbrot::SendPacket(), ns3::ndn::Consumer::SendPacket(), ns3::ndn::Subscriber::SendPacket(), ns3::ndn::ConsumerQos::SendPacket(), StartApplication(), and StopApplication().
m_face
shared_ptr<Face> ns3::ndn::App::m_face protected
Definition at line 104 of file ndn-app.hpp.
Referenced by OnData(), OnInterest(), ns3::ndn::Producer::OnInterest(), OnNack(), ns3::ndn::Aggregator::SendAggInterest(), ns3::ndn::SpontaneousProducer::SendData(), ns3::ndn::ConsumerZipfMandelbrot::SendPacket(), ns3::ndn::Consumer::SendPacket(), ns3::ndn::Subscriber::SendPacket(), ns3::ndn::ConsumerQos::SendPacket(), ns3::ndn::Aggregator::StartApplication(), StartApplication(), ns3::ndn::SpontaneousProducer::StartApplication(), ns3::ndn::Producer::StartApplication(), and StopApplication().
m_appLink
AppLinkService* ns3::ndn::App::m_appLink protected
Definition at line 105 of file ndn-app.hpp.
Referenced by ns3::ndn::Producer::OnInterest(), ns3::ndn::Aggregator::SendAggInterest(), ns3::ndn::SpontaneousProducer::SendData(), ns3::ndn::ConsumerZipfMandelbrot::SendPacket(), ns3::ndn::Consumer::SendPacket(), ns3::ndn::Subscriber::SendPacket(), ns3::ndn::ConsumerQos::SendPacket(), and StartApplication().
m_appId
uint32_t ns3::ndn::App::m_appId protected
Definition at line 107 of file ndn-app.hpp.
Referenced by DoInitialize(), and GetId().
m_receivedInterests
TracedCallback<shared_ptr<const Interest>, Ptr<App>, shared_ptr<Face> > ns3::ndn::App::m_receivedInterests protected
App-level trace of received Interests.
Definition at line 110 of file ndn-app.hpp.
Referenced by GetTypeId(), and OnInterest().
m_receivedDatas
TracedCallback<shared_ptr<const Data>, Ptr<App>, shared_ptr<Face> > ns3::ndn::App::m_receivedDatas protected
App-level trace of received Data.
Definition at line 113 of file ndn-app.hpp.
Referenced by GetTypeId(), and OnData().
m_receivedNacks
TracedCallback<shared_ptr<const lp::Nack>, Ptr<App>, shared_ptr<Face> > ns3::ndn::App::m_receivedNacks protected
App-level trace of received Nacks.
Definition at line 116 of file ndn-app.hpp.
Referenced by GetTypeId(), and OnNack().
m_transmittedInterests
TracedCallback<shared_ptr<const Interest>, Ptr<App>, shared_ptr<Face> > ns3::ndn::App::m_transmittedInterests protected
App-level trace of transmitted Interests.
Definition at line 119 of file ndn-app.hpp.
Referenced by GetTypeId(), ns3::ndn::Aggregator::SendAggInterest(), ns3::ndn::ConsumerZipfMandelbrot::SendPacket(), ns3::ndn::Consumer::SendPacket(), ns3::ndn::Subscriber::SendPacket(), and ns3::ndn::ConsumerQos::SendPacket().
m_transmittedDatas
TracedCallback<shared_ptr<const Data>, Ptr<App>, shared_ptr<Face> > ns3::ndn::App::m_transmittedDatas protected
App-level trace of transmitted Data.
Definition at line 122 of file ndn-app.hpp.
Referenced by GetTypeId(), ns3::ndn::Producer::OnInterest(), and ns3::ndn::SpontaneousProducer::SendData().
m_transmittedNacks
TracedCallback<shared_ptr<const lp::Nack>, Ptr<App>, shared_ptr<Face> > ns3::ndn::App::m_transmittedNacks protected
App-level trace of transmitted Nacks.
Definition at line 125 of file ndn-app.hpp.
Referenced by GetTypeId().
The documentation for this class was generated from the following files:
ndnSIM/apps/ndn-app.hpp
ndnSIM/apps/ndn-app.cpp