ndnSIM QoS: ns3::ndn::Producer Class Reference
ns3::ndn::Producer Class Reference
NDN applications
A simple Interest-sink applia simple Interest-sink application.
#include <ndn-producer.hpp>
Public Member Functions
Producer ()
virtual void OnInterest (shared_ptr< const Interest > interest)
Method that will be called every time new Interest arrives.
Public Member Functions inherited from ns3::ndn::App
App ()
Default constructor.
virtual ~App ()
uint32_t GetId () const
Get application ID (ID of applications face)
virtual void OnData (shared_ptr< const Data > data)
Method that will be called every time new Data arrives.
virtual void OnNack (shared_ptr< const lp::Nack > nack)
Method that will be called every time new Nack arrives.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::ndn::App
static TypeId GetTypeId ()
Protected Member Functions
virtual void StartApplication ()
Called at time specified by Start.
virtual void StopApplication ()
Called at time specified by Stop.
Protected Member Functions inherited from ns3::ndn::App
virtual void DoInitialize ()
virtual void DoDispose ()
Additional Inherited Members
Public Types inherited from ns3::ndn::App
typedef void(* InterestTraceCallback) (shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face >)
typedef void(* DataTraceCallback) (shared_ptr< const Data >, Ptr< App >, shared_ptr< Face >)
typedef void(* NackTraceCallback) (shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face >)
Protected Attributes inherited from ns3::ndn::App
bool m_active
Flag to indicate that application is active (set by StartApplication and StopApplication)
shared_ptr< Face > m_face
AppLinkService * m_appLink
uint32_t m_appId
TracedCallback< shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face > > m_receivedInterests
App-level trace of received Interests.
TracedCallback< shared_ptr< const Data >, Ptr< App >, shared_ptr< Face > > m_receivedDatas
App-level trace of received Data.
TracedCallback< shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face > > m_receivedNacks
App-level trace of received Nacks.
TracedCallback< shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face > > m_transmittedInterests
App-level trace of transmitted Interests.
TracedCallback< shared_ptr< const Data >, Ptr< App >, shared_ptr< Face > > m_transmittedDatas
App-level trace of transmitted Data.
TracedCallback< shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face > > m_transmittedNacks
App-level trace of transmitted Nacks.
Detailed Description
A simple Interest-sink applia simple Interest-sink application.
A simple Interest-sink applia simple Interest-sink application, which replying every incoming Interest with Data packet with a specified size and name same as in Interest.cation, which replying every incoming Interest with Data packet with a specified size and name same as in Interest.
Definition at line 43 of file ndn-producer.hpp.
Constructor & Destructor Documentation
Producer()
ns3::ndn::Producer::Producer ()
Definition at line 70 of file ndn-producer.cpp.
Member Function Documentation
GetTypeId()
TypeId ns3::ndn::Producer::GetTypeId (void) static
Definition at line 40 of file ndn-producer.cpp.
OnInterest()
void ns3::ndn::Producer::OnInterest (shared_ptr< const Interest > interest) virtual
Method that will be called every time new Interest arrives.
Reimplemented from ns3::ndn::App.
Definition at line 94 of file ndn-producer.cpp.
References ns3::ndn::App::GetId(), ns3::ndn::App::m_active, ns3::ndn::App::m_appLink, ns3::ndn::App::m_face, ns3::ndn::App::m_transmittedDatas, and ns3::ndn::App::OnInterest().
StartApplication()
void ns3::ndn::Producer::StartApplication () protected virtual
Called at time specified by Start.
Reimplemented from ns3::ndn::App.
Definition at line 77 of file ndn-producer.cpp.
References ns3::ndn::App::m_face, and ns3::ndn::App::StartApplication().
StopApplication()
void ns3::ndn::Producer::StopApplication () protected virtual
Called at time specified by Stop.
Reimplemented from ns3::ndn::App.
Definition at line 86 of file ndn-producer.cpp.
References ns3::ndn::App::StopApplication().
The documentation for this class was generated from the following files:
ndnSIM/apps/ndn-producer.hpp
ndnSIM/apps/ndn-producer.cpp