ndnSIM QoS: nfd::fw::asf::FaceInfo Class Reference
nfd::fw::asf::FaceInfo Class Reference
Strategy information for each face in a namespace.
#include <asf-measurements.hpp>
Classes
class Error
Public Member Functions
FaceInfo ()
~FaceInfo ()
void setTimeoutEvent (const scheduler::EventId &id, const Name &interestName)
void setMeasurementExpirationEventId (const scheduler::EventId &id)
const scheduler::EventId & getMeasurementExpirationEventId ()
void cancelTimeoutEvent (const Name &prefix)
bool isTimeoutScheduled () const
void recordRtt (const shared_ptr< pit::Entry > &pitEntry, const Face &inFace)
void recordTimeout (const Name &interestName)
bool isTimeout () const
RttEstimator::Duration computeRto () const
RttStats::Rtt getRtt () const
RttStats::Rtt getSrtt () const
bool hasSrttMeasurement () const
size_t getNSilentTimeouts () const
void setNSilentTimeouts (size_t nSilentTimeouts)
Detailed Description
Strategy information for each face in a namespace.
Definition at line 92 of file asf-measurements.hpp.
Constructor & Destructor Documentation
FaceInfo()
nfd::fw::asf::FaceInfo::FaceInfo ()
Definition at line 67 of file asf-measurements.cpp.
~FaceInfo()
nfd::fw::asf::FaceInfo::~FaceInfo ()
Definition at line 73 of file asf-measurements.cpp.
References cancelTimeoutEvent().
Member Function Documentation
setTimeoutEvent()
void nfd::fw::asf::FaceInfo::setTimeoutEvent (const scheduler::EventId & id, const Name & interestName)
Definition at line 80 of file asf-measurements.cpp.
setMeasurementExpirationEventId()
void nfd::fw::asf::FaceInfo::setMeasurementExpirationEventId (const scheduler::EventId & id) inline
Definition at line 113 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::NamespaceInfo::extendFaceInfoLifetime().
getMeasurementExpirationEventId()
const scheduler::EventId& nfd::fw::asf::FaceInfo::getMeasurementExpirationEventId () inline
Definition at line 119 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::NamespaceInfo::extendFaceInfoLifetime().
cancelTimeoutEvent()
void nfd::fw::asf::FaceInfo::cancelTimeoutEvent (const Name & prefix)
Definition at line 100 of file asf-measurements.cpp.
References cancelTimeoutEvent(), and isTimeoutScheduled().
Referenced by nfd::fw::asf::AsfStrategy::beforeSatisfyInterest(), cancelTimeoutEvent(), recordTimeout(), and ~FaceInfo().
isTimeoutScheduled()
bool nfd::fw::asf::FaceInfo::isTimeoutScheduled () const inline
Definition at line 128 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::AsfStrategy::beforeSatisfyInterest(), and cancelTimeoutEvent().
recordRtt()
void nfd::fw::asf::FaceInfo::recordRtt (const shared_ptr< pit::Entry > & pitEntry, const Face & inFace)
Definition at line 114 of file asf-measurements.cpp.
References nfd::fw::asf::RttStats::addRttMeasurement(), nfd::fw::asf::RttStats::getRtt(), and nfd::fw::asf::RttStats::getSrtt().
Referenced by nfd::fw::asf::AsfStrategy::beforeSatisfyInterest().
recordTimeout()
void nfd::fw::asf::FaceInfo::recordTimeout (const Name & interestName)
Definition at line 135 of file asf-measurements.cpp.
References cancelTimeoutEvent(), and nfd::fw::asf::RttStats::recordTimeout().
isTimeout()
bool nfd::fw::asf::FaceInfo::isTimeout () const inline
Definition at line 140 of file asf-measurements.hpp.
References getRtt(), and nfd::fw::asf::RttStats::RTT_TIMEOUT.
Referenced by nfd::fw::asf::ProbingModule::getFaceToProbe().
computeRto()
RttEstimator::Duration nfd::fw::asf::FaceInfo::computeRto () const inline
Definition at line 146 of file asf-measurements.hpp.
References nfd::fw::asf::RttStats::computeRto().
getRtt()
RttStats::Rtt nfd::fw::asf::FaceInfo::getRtt () const inline
Definition at line 152 of file asf-measurements.hpp.
References nfd::fw::asf::RttStats::getRtt().
Referenced by isTimeout().
getSrtt()
RttStats::Rtt nfd::fw::asf::FaceInfo::getSrtt () const inline
Definition at line 158 of file asf-measurements.hpp.
References nfd::fw::asf::RttStats::getSrtt().
Referenced by nfd::fw::asf::ProbingModule::getFaceToProbe(), and hasSrttMeasurement().
hasSrttMeasurement()
bool nfd::fw::asf::FaceInfo::hasSrttMeasurement () const inline
Definition at line 164 of file asf-measurements.hpp.
References getSrtt(), and nfd::fw::asf::RttStats::RTT_NO_MEASUREMENT.
Referenced by nfd::fw::asf::ProbingModule::getFaceToProbe().
getNSilentTimeouts()
size_t nfd::fw::asf::FaceInfo::getNSilentTimeouts () const inline
Definition at line 170 of file asf-measurements.hpp.
setNSilentTimeouts()
void nfd::fw::asf::FaceInfo::setNSilentTimeouts (size_t nSilentTimeouts) inline
Definition at line 176 of file asf-measurements.hpp.
The documentation for this class was generated from the following files:
ndnSIM/NFD/daemon/fw/asf-measurements.hpp
ndnSIM/NFD/daemon/fw/asf-measurements.cpp