ndnSIM QoS: nfd::fw::asf::AsfMeasurements Class Reference
nfd::fw::asf::AsfMeasurements Class Reference
Helper class to retrieve and create strategy measurements.
#include <asf-measurements.hpp>
Public Member Functions
AsfMeasurements (MeasurementsAccessor &measurements)
FaceInfo * getFaceInfo (const fib::Entry &fibEntry, const Interest &interest, FaceId faceId)
FaceInfo & getOrCreateFaceInfo (const fib::Entry &fibEntry, const Interest &interest, FaceId faceId)
NamespaceInfo * getNamespaceInfo (const Name &prefix)
NamespaceInfo & getOrCreateNamespaceInfo (const fib::Entry &fibEntry, const Interest &interest)
Static Public Attributes
static constexpr time::microseconds MEASUREMENTS_LIFETIME = 300_s
Detailed Description
Helper class to retrieve and create strategy measurements.
Definition at line 296 of file asf-measurements.hpp.
Constructor & Destructor Documentation
AsfMeasurements()
nfd::fw::asf::AsfMeasurements::AsfMeasurements (MeasurementsAccessor & measurements) explicit
Definition at line 205 of file asf-measurements.cpp.
Member Function Documentation
getFaceInfo()
FaceInfo * nfd::fw::asf::AsfMeasurements::getFaceInfo (const fib::Entry & fibEntry, const Interest & interest, FaceId faceId)
Definition at line 211 of file asf-measurements.cpp.
References nfd::fw::asf::NamespaceInfo::getFaceInfo(), and getOrCreateNamespaceInfo().
Referenced by nfd::fw::asf::ProbingModule::getFaceToProbe().
getOrCreateFaceInfo()
FaceInfo & nfd::fw::asf::AsfMeasurements::getOrCreateFaceInfo (const fib::Entry & fibEntry, const Interest & interest, FaceId faceId)
Definition at line 218 of file asf-measurements.cpp.
References nfd::fw::asf::NamespaceInfo::getOrCreateFaceInfo(), and getOrCreateNamespaceInfo().
getNamespaceInfo()
NamespaceInfo * nfd::fw::asf::AsfMeasurements::getNamespaceInfo (const Name & prefix)
Definition at line 226 of file asf-measurements.cpp.
Referenced by nfd::fw::asf::AsfStrategy::beforeSatisfyInterest(), and nfd::fw::asf::ProbingModule::scheduleProbe().
getOrCreateNamespaceInfo()
NamespaceInfo & nfd::fw::asf::AsfMeasurements::getOrCreateNamespaceInfo (const fib::Entry & fibEntry, const Interest & interest)
Definition at line 242 of file asf-measurements.cpp.
Referenced by nfd::fw::asf::ProbingModule::afterForwardingProbe(), getFaceInfo(), getOrCreateFaceInfo(), and nfd::fw::asf::ProbingModule::isProbingNeeded().
Member Data Documentation
MEASUREMENTS_LIFETIME
constexpr time::microseconds nfd::fw::asf::AsfMeasurements::MEASUREMENTS_LIFETIME = 300_s static constexpr
Definition at line 319 of file asf-measurements.hpp.
Referenced by nfd::fw::asf::NamespaceInfo::extendFaceInfoLifetime().
The documentation for this class was generated from the following files:
ndnSIM/NFD/daemon/fw/asf-measurements.hpp
ndnSIM/NFD/daemon/fw/asf-measurements.cpp