ndnSIM QoS: nfd::fw::QosQueue Class Reference
nfd::fw::QosQueue Class Reference
Class that implements QoS queue for NDN packets.
#include <ndn-qos-queue.hpp>
Public Types
typedef std::list< QueueItem > Queue
Defines basic queue structure.
Public Member Functions
QosQueue ()
Constructor.
void SetMaxQueueSize (uint32_t size)
Set the max queue size.
uint32_t GetMaxQueueSize () const
Get the queue size.
void SetWeight (float weight)
Set the wieght of the queue for WFQ.
float GetWeight ()
Get the current weight of the queue.
void SetLastVirtualFinishTime (uint64_t lvft)
Update the last virtual finish time.
uint64_t GetLastVirtualFinishTime ()
Get the last virtual finish time.
bool Enqueue (QueueItem item)
Push the given packet and corresponding metainfo onto the queue.
QueueItem Dequeue ()
Dequeue the packet currently at the top of the queue.
void DisplayQueue ()
Print the contents of the queue.
bool IsEmpty () const
Check whether queue is empty.
QueueItem GetFirstElement ()
Get the packet at the top of the queue.
Detailed Description
Class that implements QoS queue for NDN packets.
Definition at line 89 of file ndn-qos-queue.hpp.
Member Typedef Documentation
Queue
typedef std::list<QueueItem> nfd::fw::QosQueue::Queue
Defines basic queue structure.
Definition at line 159 of file ndn-qos-queue.hpp.
Constructor & Destructor Documentation
QosQueue()
nfd::fw::QosQueue::QosQueue ()
Constructor.
Definition at line 30 of file ndn-qos-queue.cpp.
Member Function Documentation
SetMaxQueueSize()
void nfd::fw::QosQueue::SetMaxQueueSize (uint32_t size)
Set the max queue size.
Parameters
size The maximum allowable size of the queue.
Definition at line 38 of file ndn-qos-queue.cpp.
GetMaxQueueSize()
uint32_t nfd::fw::QosQueue::GetMaxQueueSize () const
Get the queue size.
Definition at line 44 of file ndn-qos-queue.cpp.
Referenced by Enqueue().
SetWeight()
void nfd::fw::QosQueue::SetWeight (float weight)
Set the wieght of the queue for WFQ.
Parameters
weight The weight of the queue.
Definition at line 50 of file ndn-qos-queue.cpp.
Referenced by nfd::fw::NdnPriorityTxQueue::NdnPriorityTxQueue().
GetWeight()
float nfd::fw::QosQueue::GetWeight ()
Get the current weight of the queue.
Definition at line 56 of file ndn-qos-queue.cpp.
Referenced by nfd::fw::NdnPriorityTxQueue::GetFlowRate().
SetLastVirtualFinishTime()
void nfd::fw::QosQueue::SetLastVirtualFinishTime (uint64_t lvft)
Update the last virtual finish time.
Parameters
lvft The last virtual finish time.
Definition at line 62 of file ndn-qos-queue.cpp.
Referenced by nfd::fw::NdnPriorityTxQueue::UpdateTime().
GetLastVirtualFinishTime()
uint64_t nfd::fw::QosQueue::GetLastVirtualFinishTime ()
Get the last virtual finish time.
Definition at line 68 of file ndn-qos-queue.cpp.
Referenced by nfd::fw::NdnPriorityTxQueue::SelectQueueToSend(), and nfd::fw::NdnPriorityTxQueue::UpdateTime().
Enqueue()
bool nfd::fw::QosQueue::Enqueue (QueueItem item)
Push the given packet and corresponding metainfo onto the queue.
Parameters
Item The packet and its metainfo, incoming face, pit entry, etc.
Definition at line 74 of file ndn-qos-queue.cpp.
References GetMaxQueueSize().
Referenced by nfd::fw::NdnPriorityTxQueue::DoEnqueue().
Dequeue()
QueueItem nfd::fw::QosQueue::Dequeue ()
Dequeue the packet currently at the top of the queue.
Definition at line 94 of file ndn-qos-queue.cpp.
Referenced by nfd::fw::NdnPriorityTxQueue::DoDequeue().
DisplayQueue()
void nfd::fw::QosQueue::DisplayQueue ()
Print the contents of the queue.
Definition at line 111 of file ndn-qos-queue.cpp.
IsEmpty()
bool nfd::fw::QosQueue::IsEmpty () const
Check whether queue is empty.
Definition at line 130 of file ndn-qos-queue.cpp.
Referenced by nfd::fw::NdnPriorityTxQueue::DoDequeue(), nfd::fw::NdnPriorityTxQueue::IsEmpty(), nfd::fw::NdnPriorityTxQueue::SelectQueueToSend(), nfd::fw::NdnPriorityTxQueue::tokenReqHig(), nfd::fw::NdnPriorityTxQueue::tokenReqLow(), and nfd::fw::NdnPriorityTxQueue::tokenReqMid().
GetFirstElement()
QueueItem nfd::fw::QosQueue::GetFirstElement ()
Get the packet at the top of the queue.
Definition at line 136 of file ndn-qos-queue.cpp.
The documentation for this class was generated from the following files:
ndnSIM/NFD/daemon/fw/ndn-qos-queue.hpp
ndnSIM/NFD/daemon/fw/ndn-qos-queue.cpp