ndnSIM QoS: nfd::fw::NccStrategy Class Reference
nfd::fw::NccStrategy Class Reference
a forwarding strategy similar to CCNx 0.7.2
#include <ncc-strategy.hpp>
Classes
class MeasurementsEntryInfo
StrategyInfo on measurements::Entry.
class PitEntryInfo
StrategyInfo on pit::Entry.
Public Member Functions
NccStrategy (Forwarder &forwarder, const Name &name=getStrategyName())
virtual void afterReceiveInterest (const Face &inFace, const Interest &interest, const shared_ptr< pit::Entry > &pitEntry) override
trigger after Interest is received
virtual void beforeSatisfyInterest (const shared_ptr< pit::Entry > &pitEntry, const Face &inFace, const Data &data) override
trigger before PIT entry is satisfied
Public Member Functions inherited from nfd::fw::Strategy
Strategy (Forwarder &forwarder)
construct a strategy instance
virtual ~Strategy ()
const Name & getInstanceName () const
virtual void afterContentStoreHit (const shared_ptr< pit::Entry > &pitEntry, const Face &inFace, const Data &data)
trigger after a Data is matched in CS
virtual void afterReceiveData (const shared_ptr< pit::Entry > &pitEntry, const Face &inFace, const Data &data)
trigger after Data is received
virtual void afterReceiveNack (const Face &inFace, const lp::Nack &nack, const shared_ptr< pit::Entry > &pitEntry)
trigger after Nack is received
virtual void onDroppedInterest (const Face &outFace, const Interest &interest)
trigger after Interest dropped for exceeding allowed retransmissions
Static Public Member Functions
static const Name & getStrategyName ()
Static Public Member Functions inherited from nfd::fw::Strategy
template<typename S >
static void registerType (const Name &strategyName=S::getStrategyName())
register a strategy type
static bool canCreate (const Name &instanceName)
static unique_ptr< Strategy > create (const Name &instanceName, Forwarder &forwarder)
static bool areSameType (const Name &instanceNameA, const Name &instanceNameB)
static std::set< Name > listRegistered ()
static const Name & getStrategyName ()
Protected Member Functions
MeasurementsEntryInfo & getMeasurementsEntryInfo (measurements::Entry *entry)
MeasurementsEntryInfo & getMeasurementsEntryInfo (const shared_ptr< pit::Entry > &entry)
void doPropagate (FaceId inFaceId, weak_ptr< pit::Entry > pitEntryWeak)
propagate to another upstream
void timeoutOnBestFace (weak_ptr< pit::Entry > pitEntryWeak)
best face did not reply within prediction
Protected Member Functions inherited from nfd::fw::Strategy
void sendInterest (const shared_ptr< pit::Entry > &pitEntry, Face &outFace, const Interest &interest)
send Interest to outFace
void sendData (const shared_ptr< pit::Entry > &pitEntry, const Data &data, const Face &outFace)
send data to outFace
void sendDataToAll (const shared_ptr< pit::Entry > &pitEntry, const Face &inFace, const Data &data)
send data to all matched and qualified faces
void rejectPendingInterest (const shared_ptr< pit::Entry > &pitEntry)
schedule the PIT entry for immediate deletion
void sendNack (const shared_ptr< pit::Entry > &pitEntry, const Face &outFace, const lp::NackHeader &header)
send Nack to outFace
void sendNacks (const shared_ptr< pit::Entry > &pitEntry, const lp::NackHeader &header, std::initializer_list< const Face * > exceptFaces=std::initializer_list< const Face * >())
send Nack to every face that has an in-record, except those in exceptFaces
void setExpiryTimer (const shared_ptr< pit::Entry > &pitEntry, time::milliseconds duration)
Schedule the PIT entry to be erased after duration.
const fib::Entry & lookupFib (const pit::Entry &pitEntry) const
performs a FIB lookup, considering Link object if present
MeasurementsAccessor & getMeasurements ()
Face * getFace (FaceId id) const
const FaceTable & getFaceTable () const
void setInstanceName (const Name &name)
set strategy instance name
Static Protected Attributes
static const time::microseconds DEFER_FIRST_WITHOUT_BEST_FACE = 4_ms
static const time::microseconds DEFER_RANGE_WITHOUT_BEST_FACE = 75_ms
static const int UPDATE_MEASUREMENTS_N_LEVELS = 2
static const time::nanoseconds MEASUREMENTS_LIFETIME = 16_s
Additional Inherited Members
Static Protected Member Functions inherited from nfd::fw::Strategy
static ParsedInstanceName parseInstanceName (const Name &input)
parse a strategy instance name
static Name makeInstanceName (const Name &input, const Name &strategyName)
construct a strategy instance name
Protected Attributes inherited from nfd::fw::Strategy
signal::Signal< FaceTable, Face & > & afterAddFace
signal::Signal< FaceTable, Face & > & beforeRemoveFace
Detailed Description
a forwarding strategy similar to CCNx 0.7.2
Definition at line 36 of file ncc-strategy.hpp.
Constructor & Destructor Documentation
NccStrategy()
nfd::fw::NccStrategy::NccStrategy (Forwarder & forwarder, const Name & name = getStrategyName()) explicit
Definition at line 39 of file ncc-strategy.cpp.
References getStrategyName(), nfd::fw::Strategy::makeInstanceName(), nfd::fw::Strategy::ParsedInstanceName::parameters, nfd::fw::Strategy::parseInstanceName(), nfd::fw::Strategy::setInstanceName(), and nfd::fw::Strategy::ParsedInstanceName::version.
Member Function Documentation
getStrategyName()
const Name & nfd::fw::NccStrategy::getStrategyName () static
Definition at line 54 of file ncc-strategy.cpp.
Referenced by NccStrategy().
afterReceiveInterest()
void nfd::fw::NccStrategy::afterReceiveInterest (const Face & inFace, const Interest & interest, const shared_ptr< pit::Entry > & pitEntry) override virtual
trigger after Interest is received
The Interest:
does not violate Scope
is not looped
cannot be satisfied by ContentStore
is under a namespace managed by this strategy
The PIT entry is set to expire after InterestLifetime has elapsed at each downstream.
The strategy should decide whether and where to forward this Interest.
If the strategy decides to forward this Interest, invoke sendInterest for each upstream, either now or shortly after via a scheduler event, but before PIT entry expires. Optionally, the strategy can invoke setExpiryTimer to adjust how long it would wait for a response.
If the strategy has already forwarded this Interest previously and decides to continue waiting, do nothing. Optionally, the strategy can invoke setExpiryTimer to adjust how long it would wait for a response.
If the strategy concludes that this Interest cannot be satisfied, invoke rejectPendingInterest to erase the PIT entry.
Warning
The strategy must not retain shared_ptr<pit::Entry>, otherwise undefined behavior may occur. However, the strategy is allowed to store weak_ptr<pit::Entry>.
Implements nfd::fw::Strategy.
Definition at line 61 of file ncc-strategy.cpp.
References nfd::fw::NccStrategy::PitEntryInfo::bestFaceTimeout, nfd::fw::canForwardToLegacy(), DEFER_FIRST_WITHOUT_BEST_FACE, DEFER_RANGE_WITHOUT_BEST_FACE, doPropagate(), nfd::fw::NccStrategy::MeasurementsEntryInfo::getBestFace(), getMeasurementsEntryInfo(), nfd::fw::hasPendingOutRecords(), nfd::fw::Strategy::lookupFib(), nfd::fw::NccStrategy::PitEntryInfo::maxInterval, nfd::fw::NccStrategy::MeasurementsEntryInfo::prediction, nfd::fw::NccStrategy::MeasurementsEntryInfo::previousFace, nfd::fw::NccStrategy::PitEntryInfo::propagateTimer, nfd::fw::Strategy::rejectPendingInterest(), nfd::fw::Strategy::sendInterest(), timeoutOnBestFace(), and nfd::fw::wouldViolateScope().
beforeSatisfyInterest()
void nfd::fw::NccStrategy::beforeSatisfyInterest (const shared_ptr< pit::Entry > & pitEntry, const Face & inFace, const Data & data) override virtual
trigger before PIT entry is satisfied
This trigger is invoked when an incoming Data satisfies more than one PIT entry. The strategy can collect measurements information, but cannot manipulate Data forwarding. When an incoming Data satisfies only one PIT entry, afterReceiveData is invoked instead and given full control over Data forwarding. If a strategy does not override afterReceiveData, the default implementation invokes beforeSatisfyInterest.
Normally, PIT entries would be erased after receiving the first matching Data. If the strategy wishes to collect responses from additional upstream nodes, it should invoke setExpiryTimer within this function to prolong the PIT entry lifetime. If a Data arrives from another upstream during the extended PIT entry lifetime, this trigger will be invoked again. At that time, this function must invoke setExpiryTimer again to continue collecting more responses.
In this base class this method does nothing.
Warning
The strategy must not retain shared_ptr<pit::Entry>, otherwise undefined behavior may occur. However, the strategy is allowed to store weak_ptr<pit::Entry>.
Reimplemented from nfd::fw::Strategy.
Definition at line 209 of file ncc-strategy.cpp.
References nfd::fw::NccStrategy::PitEntryInfo::bestFaceTimeout, nfd::fw::NccStrategy::MeasurementsEntryInfo::getBestFace(), nfd::fw::Strategy::getMeasurements(), getMeasurementsEntryInfo(), MEASUREMENTS_LIFETIME, nfd::fw::NccStrategy::PitEntryInfo::propagateTimer, UPDATE_MEASUREMENTS_N_LEVELS, and nfd::fw::NccStrategy::MeasurementsEntryInfo::updateBestFace().
getMeasurementsEntryInfo() [1/2]
NccStrategy::MeasurementsEntryInfo & nfd::fw::NccStrategy::getMeasurementsEntryInfo (measurements::Entry * entry) protected
Definition at line 254 of file ncc-strategy.cpp.
References nfd::fw::Strategy::getMeasurements(), and nfd::fw::NccStrategy::MeasurementsEntryInfo::inheritFrom().
Referenced by afterReceiveInterest(), beforeSatisfyInterest(), doPropagate(), getMeasurementsEntryInfo(), and timeoutOnBestFace().
getMeasurementsEntryInfo() [2/2]
NccStrategy::MeasurementsEntryInfo & nfd::fw::NccStrategy::getMeasurementsEntryInfo (const shared_ptr< pit::Entry > & entry) protected
Definition at line 247 of file ncc-strategy.cpp.
References nfd::fw::Strategy::getMeasurements(), and getMeasurementsEntryInfo().
doPropagate()
void nfd::fw::NccStrategy::doPropagate (FaceId inFaceId, weak_ptr< pit::Entry > pitEntryWeak) protected
propagate to another upstream
Definition at line 135 of file ncc-strategy.cpp.
References nfd::fw::canForwardToLegacy(), nfd::fw::Strategy::getFace(), getMeasurementsEntryInfo(), nfd::fw::Strategy::lookupFib(), nfd::fw::NccStrategy::PitEntryInfo::maxInterval, nfd::fw::NccStrategy::MeasurementsEntryInfo::previousFace, nfd::fw::NccStrategy::PitEntryInfo::propagateTimer, nfd::fw::Strategy::sendInterest(), and nfd::fw::wouldViolateScope().
Referenced by afterReceiveInterest().
timeoutOnBestFace()
void nfd::fw::NccStrategy::timeoutOnBestFace (weak_ptr< pit::Entry > pitEntryWeak) protected
best face did not reply within prediction
Definition at line 186 of file ncc-strategy.cpp.
References nfd::fw::NccStrategy::MeasurementsEntryInfo::adjustPredictUp(), nfd::fw::Strategy::getMeasurements(), getMeasurementsEntryInfo(), MEASUREMENTS_LIFETIME, and UPDATE_MEASUREMENTS_N_LEVELS.
Referenced by afterReceiveInterest().
Member Data Documentation
DEFER_FIRST_WITHOUT_BEST_FACE
const time::microseconds nfd::fw::NccStrategy::DEFER_FIRST_WITHOUT_BEST_FACE = 4_ms static protected
Definition at line 135 of file ncc-strategy.hpp.
Referenced by afterReceiveInterest().
DEFER_RANGE_WITHOUT_BEST_FACE
const time::microseconds nfd::fw::NccStrategy::DEFER_RANGE_WITHOUT_BEST_FACE = 75_ms static protected
Definition at line 136 of file ncc-strategy.hpp.
Referenced by afterReceiveInterest().
UPDATE_MEASUREMENTS_N_LEVELS
const int nfd::fw::NccStrategy::UPDATE_MEASUREMENTS_N_LEVELS = 2 static protected
Definition at line 137 of file ncc-strategy.hpp.
Referenced by beforeSatisfyInterest(), and timeoutOnBestFace().
MEASUREMENTS_LIFETIME
const time::nanoseconds nfd::fw::NccStrategy::MEASUREMENTS_LIFETIME = 16_s static protected
Definition at line 138 of file ncc-strategy.hpp.
Referenced by beforeSatisfyInterest(), and timeoutOnBestFace().
The documentation for this class was generated from the following files:
ndnSIM/NFD/daemon/fw/ncc-strategy.hpp
ndnSIM/NFD/daemon/fw/ncc-strategy.cpp