ndnSIM QoS: ns3::ndn::Synchronizer Class Reference
ns3::ndn::Synchronizer Class Reference abstract
#include <ndn-synchronizer.hpp>
Public Member Functions
Synchronizer ()
Constructor.
void addSender (int node, Ptr< ConsumerQos > sender)
Add a reference to the consumer application of a sending node.
void syncEvent ()
Pause te simulation and perform synching operations.
virtual void addArrivedPackets (std::string)
Save information on recieved packet.
void setTimeStep (double step)
Set how often we pause the simulation to perform sync operations.
void beginSync ()
Begin synching operations.
void injectInterests (bool agg)
inject interests as descibed by th packetNames vector
std::vector< std::string > SplitString (std::string strLine, int limit)
virtual void sendSync ()=0
virtual void receiveSync ()=0
Protected Attributes
std::unordered_map< int, Ptr< ConsumerQos > > senders
std::vector< std::string > arrivedPackets
std::vector< std::string > packetNames
double timestep
Detailed Description
Definition at line 32 of file ndn-synchronizer.hpp.
Constructor & Destructor Documentation
Synchronizer()
ns3::ndn::Synchronizer::Synchronizer ()
Constructor.
Definition at line 35 of file ndn-synchronizer.cpp.
References timestep.
Member Function Documentation
addSender()
void ns3::ndn::Synchronizer::addSender (int node, Ptr< ConsumerQos > sender)
Add a reference to the consumer application of a sending node.
Parameters
node the node to which the appliaction belongs to
sender reference to the appliaction instance
Definition at line 41 of file ndn-synchronizer.cpp.
References senders.
syncEvent()
void ns3::ndn::Synchronizer::syncEvent ()
Pause te simulation and perform synching operations.
Definition at line 74 of file ndn-synchronizer.cpp.
References injectInterests(), receiveSync(), sendSync(), and timestep.
Referenced by beginSync().
addArrivedPackets()
void ns3::ndn::Synchronizer::addArrivedPackets (std::string str) virtual
Save information on recieved packet.
Parameters
string string with information on the arriving interest.
Reimplemented in ns3::ndn::SyncSocket.
Definition at line 62 of file ndn-synchronizer.cpp.
References arrivedPackets.
setTimeStep()
void ns3::ndn::Synchronizer::setTimeStep (double step)
Set how often we pause the simulation to perform sync operations.
Parameters
step seconds between sync operations
Definition at line 56 of file ndn-synchronizer.cpp.
References timestep.
beginSync()
void ns3::ndn::Synchronizer::beginSync ()
Begin synching operations.
Definition at line 68 of file ndn-synchronizer.cpp.
References syncEvent().
injectInterests()
void ns3::ndn::Synchronizer::injectInterests (bool agg)
inject interests as descibed by th packetNames vector
Parameters
agg should interests at the same node be aggregated
Definition at line 87 of file ndn-synchronizer.cpp.
References packetNames, senders, ns3::ndn::ConsumerQos::SendPacket(), and SplitString().
Referenced by syncEvent().
SplitString()
std::vector< std::string > ns3::ndn::Synchronizer::SplitString (std::string strLine, int limit)
Definition at line 100 of file ndn-synchronizer.cpp.
Referenced by injectInterests().
sendSync()
virtual void ns3::ndn::Synchronizer::sendSync () pure virtual
Implemented in ns3::ndn::SyncSocket.
Referenced by syncEvent().
receiveSync()
virtual void ns3::ndn::Synchronizer::receiveSync () pure virtual
Implemented in ns3::ndn::SyncSocket.
Referenced by syncEvent().
Member Data Documentation
senders
std::unordered_map<int,Ptr<ConsumerQos> > ns3::ndn::Synchronizer::senders protected
Definition at line 91 of file ndn-synchronizer.hpp.
Referenced by addSender(), and injectInterests().
arrivedPackets
std::vector<std::string> ns3::ndn::Synchronizer::arrivedPackets protected
Definition at line 93 of file ndn-synchronizer.hpp.
Referenced by addArrivedPackets().
packetNames
std::vector<std::string> ns3::ndn::Synchronizer::packetNames protected
Definition at line 95 of file ndn-synchronizer.hpp.
Referenced by injectInterests().
timestep
double ns3::ndn::Synchronizer::timestep protected
Definition at line 97 of file ndn-synchronizer.hpp.
Referenced by setTimeStep(), syncEvent(), and Synchronizer().
The documentation for this class was generated from the following files:
ndnSIM/apps/ndn-synchronizer.hpp
ndnSIM/apps/ndn-synchronizer.cpp