ndnSIM QoS: nfd::fw::RetxSuppressionExponential Class Reference
nfd::fw::RetxSuppressionExponential Class Reference
a retransmission suppression decision algorithm that suppresses retransmissions using exponential backoff
#include <retx-suppression-exponential.hpp>
Classes
class PitInfo
Public Types
typedef time::microseconds Duration
time granularity
Public Member Functions
RetxSuppressionExponential (const Duration &initialInterval=DEFAULT_INITIAL_INTERVAL, float multiplier=DEFAULT_MULTIPLIER, const Duration &maxInterval=DEFAULT_MAX_INTERVAL)
RetxSuppressionResult decidePerPitEntry (pit::Entry &pitEntry)
determines whether Interest is a retransmission per pit entry and if so, whether it shall be forwarded or suppressed
RetxSuppressionResult decidePerUpstream (pit::Entry &pitEntry, Face &outFace)
determines whether Interest is a retransmission per upstream and if so, whether it shall be forwarded or suppressed
void incrementIntervalForOutRecord (pit::OutRecord &outRecord)
Increment the suppression interval for out record.
Static Public Attributes
static const Duration DEFAULT_INITIAL_INTERVAL = 1_ms
static const float DEFAULT_MULTIPLIER = 2.0f
static const Duration DEFAULT_MAX_INTERVAL = 250_ms
Detailed Description
a retransmission suppression decision algorithm that suppresses retransmissions using exponential backoff
The i-th retransmission will be suppressed if the last transmission (out-record) occurred within MIN(initialInterval * multiplier^(i-1), maxInterval)
Definition at line 41 of file retx-suppression-exponential.hpp.
Member Typedef Documentation
Duration
typedef time::microseconds nfd::fw::RetxSuppressionExponential::Duration
time granularity
Definition at line 46 of file retx-suppression-exponential.hpp.
Constructor & Destructor Documentation
RetxSuppressionExponential()
nfd::fw::RetxSuppressionExponential::RetxSuppressionExponential (const Duration & initialInterval = DEFAULT_INITIAL_INTERVAL, float multiplier = DEFAULT_MULTIPLIER, const Duration & maxInterval = DEFAULT_MAX_INTERVAL) explicit
Definition at line 57 of file retx-suppression-exponential.cpp.
Member Function Documentation
decidePerPitEntry()
RetxSuppressionResult nfd::fw::RetxSuppressionExponential::decidePerPitEntry (pit::Entry & pitEntry)
determines whether Interest is a retransmission per pit entry and if so, whether it shall be forwarded or suppressed
Definition at line 70 of file retx-suppression-exponential.cpp.
References nfd::fw::FORWARD, nfd::fw::getLastOutgoing(), nfd::fw::hasPendingOutRecords(), nfd::fw::NEW, nfd::fw::SUPPRESS, and nfd::fw::RetxSuppressionExponential::PitInfo::suppressionInterval.
Referenced by nfd::fw::asf::AsfStrategy::afterReceiveInterest(), nfd::fw::BestRouteStrategy2::afterReceiveInterest(), and nfd::fw::QosStrategy::afterReceiveInterest().
decidePerUpstream()
RetxSuppressionResult nfd::fw::RetxSuppressionExponential::decidePerUpstream (pit::Entry & pitEntry, Face & outFace)
determines whether Interest is a retransmission per upstream and if so, whether it shall be forwarded or suppressed
Definition at line 95 of file retx-suppression-exponential.cpp.
References nfd::fw::FORWARD, nfd::fw::NEW, nfd::fw::SUPPRESS, and nfd::fw::RetxSuppressionExponential::PitInfo::suppressionInterval.
Referenced by nfd::fw::MulticastStrategy::afterReceiveInterest(), and nfd::fw::QosStrategy::afterReceiveInterest().
incrementIntervalForOutRecord()
void nfd::fw::RetxSuppressionExponential::incrementIntervalForOutRecord (pit::OutRecord & outRecord)
Increment the suppression interval for out record.
Definition at line 119 of file retx-suppression-exponential.cpp.
References nfd::fw::RetxSuppressionExponential::PitInfo::suppressionInterval.
Referenced by nfd::fw::MulticastStrategy::afterReceiveInterest(), and nfd::fw::QosStrategy::afterReceiveInterest().
Member Data Documentation
DEFAULT_INITIAL_INTERVAL
const RetxSuppressionExponential::Duration nfd::fw::RetxSuppressionExponential::DEFAULT_INITIAL_INTERVAL = 1_ms static
Definition at line 76 of file retx-suppression-exponential.hpp.
DEFAULT_MULTIPLIER
const float nfd::fw::RetxSuppressionExponential::DEFAULT_MULTIPLIER = 2.0f static
Definition at line 77 of file retx-suppression-exponential.hpp.
DEFAULT_MAX_INTERVAL
const RetxSuppressionExponential::Duration nfd::fw::RetxSuppressionExponential::DEFAULT_MAX_INTERVAL = 250_ms static
Definition at line 78 of file retx-suppression-exponential.hpp.
The documentation for this class was generated from the following files:
ndnSIM/NFD/daemon/fw/retx-suppression-exponential.hpp
ndnSIM/NFD/daemon/fw/retx-suppression-exponential.cpp