ndnSIM QoS: ns3::ndn::QoSProducer Class Reference
ns3::ndn::QoSProducer Class Reference
A producer which can receive and process payloaded interests.
#include <ndn-QoS-producer.hpp>
Public Types
typedef void(* ReceivedInterestTraceCallback) (uint32_t, shared_ptr< const Interest >)
typedef void(* SentDataTraceCallback) (uint32_t, shared_ptr< const Data >)
Public Types inherited from ns3::ndn::App
typedef void(* InterestTraceCallback) (shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face >)
typedef void(* DataTraceCallback) (shared_ptr< const Data >, Ptr< App >, shared_ptr< Face >)
typedef void(* NackTraceCallback) (shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face >)
Public Member Functions
QoSProducer ()
Default constructor for the class.
virtual void OnInterest (shared_ptr< const Interest > interest)
Method that will be called every time new Interest arrives.
void SendData (const Name &dataName)
Send data to subscribed nodes or send out ack.
void SendTimeout ()
Public Member Functions inherited from ns3::ndn::App
App ()
Default constructor.
virtual ~App ()
uint32_t GetId () const
Get application ID (ID of applications face)
virtual void OnData (shared_ptr< const Data > data)
Method that will be called every time new Data arrives.
virtual void OnNack (shared_ptr< const lp::Nack > nack)
Method that will be called every time new Nack arrives.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::ndn::App
static TypeId GetTypeId ()
Protected Member Functions
virtual void StartApplication ()
Called at time specified by Start.
virtual void StopApplication ()
Called at time specified by Stop.
Protected Member Functions inherited from ns3::ndn::App
virtual void DoInitialize ()
virtual void DoDispose ()
Protected Attributes
TracedCallback< uint32_t, shared_ptr< const Interest > > m_receivedInterest
TracedCallback< uint32_t, shared_ptr< const Data > > m_sentData
Protected Attributes inherited from ns3::ndn::App
bool m_active
Flag to indicate that application is active (set by StartApplication and StopApplication)
shared_ptr< Face > m_face
AppLinkService * m_appLink
uint32_t m_appId
TracedCallback< shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face > > m_receivedInterests
App-level trace of received Interests.
TracedCallback< shared_ptr< const Data >, Ptr< App >, shared_ptr< Face > > m_receivedDatas
App-level trace of received Data.
TracedCallback< shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face > > m_receivedNacks
App-level trace of received Nacks.
TracedCallback< shared_ptr< const Interest >, Ptr< App >, shared_ptr< Face > > m_transmittedInterests
App-level trace of transmitted Interests.
TracedCallback< shared_ptr< const Data >, Ptr< App >, shared_ptr< Face > > m_transmittedDatas
App-level trace of transmitted Data.
TracedCallback< shared_ptr< const lp::Nack >, Ptr< App >, shared_ptr< Face > > m_transmittedNacks
App-level trace of transmitted Nacks.
Detailed Description
A producer which can receive and process payloaded interests.
When the producer receives a payloaded interest, it will only respond with an ack.
It also has the ability to publish content at a given frequency to consmers that have subscribed to it. This published content will be sent out to consumers without needing a corresponding interest.
Definition at line 46 of file ndn-QoS-producer.hpp.
Member Typedef Documentation
ReceivedInterestTraceCallback
typedef void(* ns3::ndn::QoSProducer::ReceivedInterestTraceCallback) (uint32_t, shared_ptr< const Interest >)
Definition at line 68 of file ndn-QoS-producer.hpp.
SentDataTraceCallback
typedef void(* ns3::ndn::QoSProducer::SentDataTraceCallback) (uint32_t, shared_ptr< const Data >)
Definition at line 69 of file ndn-QoS-producer.hpp.
Constructor & Destructor Documentation
QoSProducer()
ns3::ndn::QoSProducer::QoSProducer ()
Default constructor for the class.
Definition at line 84 of file ndn-QoS-producer.cpp.
Member Function Documentation
GetTypeId()
TypeId ns3::ndn::QoSProducer::GetTypeId (void) static
Definition at line 42 of file ndn-QoS-producer.cpp.
References m_receivedInterest, and m_sentData.
OnInterest()
void ns3::ndn::QoSProducer::OnInterest (shared_ptr< const Interest > interest) virtual
Method that will be called every time new Interest arrives.
Reimplemented from ns3::ndn::App.
Definition at line 115 of file ndn-QoS-producer.cpp.
References ns3::ndn::App::GetId(), ns3::ndn::App::m_active, m_receivedInterest, ns3::ndn::App::OnInterest(), and SendData().
SendData()
void ns3::ndn::QoSProducer::SendData (const Name & dataName)
Send data to subscribed nodes or send out ack.
Definition at line 166 of file ndn-QoS-producer.cpp.
References ns3::ndn::App::GetId(), ns3::ndn::App::m_active, ns3::ndn::App::m_appLink, ns3::ndn::App::m_face, m_sentData, and ns3::ndn::App::m_transmittedDatas.
Referenced by OnInterest(), and SendTimeout().
SendTimeout()
void ns3::ndn::QoSProducer::SendTimeout ()
Definition at line 141 of file ndn-QoS-producer.cpp.
References SendData().
Referenced by StartApplication().
StartApplication()
void ns3::ndn::QoSProducer::StartApplication () protected virtual
Called at time specified by Start.
Reimplemented from ns3::ndn::App.
Definition at line 95 of file ndn-QoS-producer.cpp.
References ns3::ndn::App::m_face, SendTimeout(), and ns3::ndn::App::StartApplication().
StopApplication()
void ns3::ndn::QoSProducer::StopApplication () protected virtual
Called at time specified by Stop.
Reimplemented from ns3::ndn::App.
Definition at line 108 of file ndn-QoS-producer.cpp.
References ns3::ndn::App::StopApplication().
Member Data Documentation
m_receivedInterest
TracedCallback< uint32_t, shared_ptr<const Interest> > ns3::ndn::QoSProducer::m_receivedInterest protected
Definition at line 96 of file ndn-QoS-producer.hpp.
Referenced by GetTypeId(), and OnInterest().
m_sentData
TracedCallback< uint32_t, shared_ptr<const Data> > ns3::ndn::QoSProducer::m_sentData protected
Definition at line 97 of file ndn-QoS-producer.hpp.
Referenced by GetTypeId(), and SendData().
The documentation for this class was generated from the following files:
ndnSIM/apps/ndn-QoS-producer.hpp
ndnSIM/apps/ndn-QoS-producer.cpp