ndnSIM QoS: nfd::fw::Strategy Class Reference
nfd::fw::Strategy Class Reference abstract
represents a forwarding strategy
#include <strategy.hpp>
Classes
struct ParsedInstanceName
Public Member Functions
Strategy (Forwarder &forwarder)
construct a strategy instance
virtual ~Strategy ()
const Name & getInstanceName () const
virtual void afterReceiveInterest (const Face &inFace, const Interest &interest, const shared_ptr< pit::Entry > &pitEntry)=0
trigger after Interest is received
virtual void beforeSatisfyInterest (const shared_ptr< pit::Entry > &pitEntry, const Face &inFace, const Data &data)
trigger before PIT entry is satisfied
virtual void afterContentStoreHit (const shared_ptr< pit::Entry > &pitEntry, const Face &inFace, const Data &data)
trigger after a Data is matched in CS
virtual void afterReceiveData (const shared_ptr< pit::Entry > &pitEntry, const Face &inFace, const Data &data)
trigger after Data is received
virtual void afterReceiveNack (const Face &inFace, const lp::Nack &nack, const shared_ptr< pit::Entry > &pitEntry)
trigger after Nack is received
virtual void onDroppedInterest (const Face &outFace, const Interest &interest)
trigger after Interest dropped for exceeding allowed retransmissions
Static Public Member Functions
template<typename S >
static void registerType (const Name &strategyName=S::getStrategyName())
register a strategy type
static bool canCreate (const Name &instanceName)
static unique_ptr< Strategy > create (const Name &instanceName, Forwarder &forwarder)
static bool areSameType (const Name &instanceNameA, const Name &instanceNameB)
static std::set< Name > listRegistered ()
static const Name & getStrategyName ()
Protected Member Functions
void sendInterest (const shared_ptr< pit::Entry > &pitEntry, Face &outFace, const Interest &interest)
send Interest to outFace
void sendData (const shared_ptr< pit::Entry > &pitEntry, const Data &data, const Face &outFace)
send data to outFace
void sendDataToAll (const shared_ptr< pit::Entry > &pitEntry, const Face &inFace, const Data &data)
send data to all matched and qualified faces
void rejectPendingInterest (const shared_ptr< pit::Entry > &pitEntry)
schedule the PIT entry for immediate deletion
void sendNack (const shared_ptr< pit::Entry > &pitEntry, const Face &outFace, const lp::NackHeader &header)
send Nack to outFace
void sendNacks (const shared_ptr< pit::Entry > &pitEntry, const lp::NackHeader &header, std::initializer_list< const Face * > exceptFaces=std::initializer_list< const Face * >())
send Nack to every face that has an in-record, except those in exceptFaces
void setExpiryTimer (const shared_ptr< pit::Entry > &pitEntry, time::milliseconds duration)
Schedule the PIT entry to be erased after duration.
const fib::Entry & lookupFib (const pit::Entry &pitEntry) const
performs a FIB lookup, considering Link object if present
MeasurementsAccessor & getMeasurements ()
Face * getFace (FaceId id) const
const FaceTable & getFaceTable () const
void setInstanceName (const Name &name)
set strategy instance name
Static Protected Member Functions
static ParsedInstanceName parseInstanceName (const Name &input)
parse a strategy instance name
static Name makeInstanceName (const Name &input, const Name &strategyName)
construct a strategy instance name
Protected Attributes
signal::Signal< FaceTable, Face & > & afterAddFace
signal::Signal< FaceTable, Face & > & beforeRemoveFace
Detailed Description
represents a forwarding strategy
Definition at line 37 of file strategy.hpp.
Constructor & Destructor Documentation
Strategy()
nfd::fw::Strategy::Strategy (Forwarder & forwarder) explicit
construct a strategy instance
Parameters
forwarder a reference to the forwarder, used to enable actions and accessors.
Note
Strategy subclass constructor should not retain a reference to the forwarder.
Definition at line 142 of file strategy.cpp.
~Strategy()
nfd::fw::Strategy::~Strategy () virtual default
Member Function Documentation
registerType()
template<typename S > static void nfd::fw::Strategy::registerType (const Name & strategyName = S::getStrategyName()) inline static
register a strategy type
Template Parameters
S subclass of Strategy
Parameters
strategyName strategy program name, must contain version
Note
It is permitted to register the same strategy type under multiple names, which is useful in tests and for creating aliases.
Definition at line 48 of file strategy.hpp.
canCreate()
bool nfd::fw::Strategy::canCreate (const Name & instanceName) static
Returns
whether a strategy instance can be created from instanceName
Parameters
instanceName strategy instance name, may contain version and parameters
Note
This function finds a strategy type using same rules as create , but does not attempt to construct an instance.
Definition at line 85 of file strategy.cpp.
create()
unique_ptr< Strategy > nfd::fw::Strategy::create (const Name & instanceName, Forwarder & forwarder) static
Returns
a strategy instance created from instanceName
Return values
nullptr if !canCreate(instanceName)
Exceptions
std::invalid_argument strategy type constructor does not accept specified version or parameters
Definition at line 91 of file strategy.cpp.
areSameType()
bool nfd::fw::Strategy::areSameType (const Name & instanceNameA, const Name & instanceNameB) static
Returns
whether instanceNameA and instanceNameA will initiate same strategy type
Definition at line 107 of file strategy.cpp.
listRegistered()
std::set< Name > nfd::fw::Strategy::listRegistered () static
Returns
registered versioned strategy names
Definition at line 113 of file strategy.cpp.
getStrategyName()
static const Name& nfd::fw::Strategy::getStrategyName () static
Returns
strategy program name
The strategy name is defined by the strategy program. It must end with a version component.
getInstanceName()
const Name& nfd::fw::Strategy::getInstanceName () const inline
Returns
strategy instance name
The instance name is assigned during instantiation. It contains a version component, and may have extra parameter components.
Definition at line 110 of file strategy.hpp.
afterReceiveInterest()
virtual void nfd::fw::Strategy::afterReceiveInterest (const Face & inFace, const Interest & interest, const shared_ptr< pit::Entry > & pitEntry) pure virtual
trigger after Interest is received
The Interest:
does not violate Scope
is not looped
cannot be satisfied by ContentStore
is under a namespace managed by this strategy
The PIT entry is set to expire after InterestLifetime has elapsed at each downstream.
The strategy should decide whether and where to forward this Interest.
If the strategy decides to forward this Interest, invoke sendInterest for each upstream, either now or shortly after via a scheduler event, but before PIT entry expires. Optionally, the strategy can invoke setExpiryTimer to adjust how long it would wait for a response.
If the strategy has already forwarded this Interest previously and decides to continue waiting, do nothing. Optionally, the strategy can invoke setExpiryTimer to adjust how long it would wait for a response.
If the strategy concludes that this Interest cannot be satisfied, invoke rejectPendingInterest to erase the PIT entry.
Warning
The strategy must not retain shared_ptr<pit::Entry>, otherwise undefined behavior may occur. However, the strategy is allowed to store weak_ptr<pit::Entry>.
Implemented in nfd::fw::SelfLearningStrategy, nfd::fw::QosStrategy, nfd::fw::NccStrategy, nfd::fw::MulticastStrategy, nfd::fw::BestRouteStrategy2, nfd::fw::BestRouteStrategyBase, nfd::fw::asf::AsfStrategy, and nfd::fw::AccessStrategy.
beforeSatisfyInterest()
void nfd::fw::Strategy::beforeSatisfyInterest (const shared_ptr< pit::Entry > & pitEntry, const Face & inFace, const Data & data) virtual
trigger before PIT entry is satisfied
This trigger is invoked when an incoming Data satisfies more than one PIT entry. The strategy can collect measurements information, but cannot manipulate Data forwarding. When an incoming Data satisfies only one PIT entry, afterReceiveData is invoked instead and given full control over Data forwarding. If a strategy does not override afterReceiveData, the default implementation invokes beforeSatisfyInterest.
Normally, PIT entries would be erased after receiving the first matching Data. If the strategy wishes to collect responses from additional upstream nodes, it should invoke setExpiryTimer within this function to prolong the PIT entry lifetime. If a Data arrives from another upstream during the extended PIT entry lifetime, this trigger will be invoked again. At that time, this function must invoke setExpiryTimer again to continue collecting more responses.
In this base class this method does nothing.
Warning
The strategy must not retain shared_ptr<pit::Entry>, otherwise undefined behavior may occur. However, the strategy is allowed to store weak_ptr<pit::Entry>.
Reimplemented in nfd::fw::NccStrategy, nfd::fw::asf::AsfStrategy, and nfd::fw::AccessStrategy.
Definition at line 153 of file strategy.cpp.
Referenced by nfd::fw::QosStrategy::afterReceiveData(), and afterReceiveData().
afterContentStoreHit()
void nfd::fw::Strategy::afterContentStoreHit (const shared_ptr< pit::Entry > & pitEntry, const Face & inFace, const Data & data) virtual
trigger after a Data is matched in CS
In the base class this method sends data to inFace
Definition at line 161 of file strategy.cpp.
References sendData().
afterReceiveData()
void nfd::fw::Strategy::afterReceiveData (const shared_ptr< pit::Entry > & pitEntry, const Face & inFace, const Data & data) virtual
trigger after Data is received
This trigger is invoked when an incoming Data satisfies exactly one PIT entry, and gives the strategy full control over Data forwarding.
When this trigger is invoked:
The Data has been verified to satisfy the PIT entry.
The PIT entry expiry timer is set to now
Within this function:
A strategy should return Data to downstream nodes via sendData or sendDataToAll.
A strategy can modify the Data as long as it still satisfies the PIT entry, such as adding or removing congestion marks.
A strategy can delay Data forwarding by prolonging the PIT entry lifetime via setExpiryTimer, and forward Data before the PIT entry is erased.
A strategy can collect measurements about the upstream.
A strategy can collect responses from additional upstream nodes by prolonging the PIT entry lifetime via setExpiryTimer every time a Data is received. Note that only one Data should be returned to each downstream node.
In the base class this method invokes beforeSatisfyInterest trigger and then returns the Data to downstream faces via sendDataToAll.
Reimplemented in nfd::fw::SelfLearningStrategy, and nfd::fw::QosStrategy.
Definition at line 171 of file strategy.cpp.
References beforeSatisfyInterest(), and sendDataToAll().
afterReceiveNack()
void nfd::fw::Strategy::afterReceiveNack (const Face & inFace, const lp::Nack & nack, const shared_ptr< pit::Entry > & pitEntry) virtual
trigger after Nack is received
This trigger is invoked when an incoming Nack is received in response to an forwarded Interest. The Nack has been confirmed to be a response to the last Interest forwarded to that upstream, i.e. the PIT out-record exists and has a matching Nonce. The NackHeader has been recorded in the PIT out-record.
If the PIT entry is not yet satisfied, its expiry timer remains unchanged. Otherwise, the PIT entry normally would expire immediately after this function returns.
If the strategy wishes to collect responses from additional upstream nodes, it should invoke setExpiryTimer within this function to retain the PIT entry. If a Nack arrives from another upstream during the extended PIT entry lifetime, this trigger will be invoked again. At that time, this function must invoke setExpiryTimer again to continue collecting more responses.
In the base class this method does nothing.
Warning
The strategy must not retain shared_ptr<pit::Entry>, otherwise undefined behavior may occur. However, the strategy is allowed to store weak_ptr<pit::Entry>.
Reimplemented in nfd::fw::SelfLearningStrategy, nfd::fw::QosStrategy, nfd::fw::MulticastStrategy, nfd::fw::BestRouteStrategy2, and nfd::fw::asf::AsfStrategy.
Definition at line 183 of file strategy.cpp.
onDroppedInterest()
void nfd::fw::Strategy::onDroppedInterest (const Face & outFace, const Interest & interest) virtual
trigger after Interest dropped for exceeding allowed retransmissions
In the base class this method does nothing.
Definition at line 191 of file strategy.cpp.
sendInterest()
void nfd::fw::Strategy::sendInterest (const shared_ptr< pit::Entry > & pitEntry, Face & outFace, const Interest & interest) inline protected
send Interest to outFace
Parameters
pitEntry PIT entry
outFace face through which to send out the Interest
interest the Interest packet
Definition at line 241 of file strategy.hpp.
Referenced by nfd::fw::BestRouteStrategyBase::afterReceiveInterest(), nfd::fw::BestRouteStrategy2::afterReceiveInterest(), nfd::fw::MulticastStrategy::afterReceiveInterest(), nfd::fw::NccStrategy::afterReceiveInterest(), nfd::fw::NccStrategy::doPropagate(), and nfd::fw::QosStrategy::prioritySendInterest().
sendData()
void nfd::fw::Strategy::sendData (const shared_ptr< pit::Entry > & pitEntry, const Data & data, const Face & outFace) protected
send data to outFace
Parameters
pitEntry PIT entry
data the Data packet
outFace face through which to send out the Data
Definition at line 197 of file strategy.cpp.
Referenced by afterContentStoreHit(), nfd::fw::QosStrategy::prioritySendData(), and sendDataToAll().
sendDataToAll()
void nfd::fw::Strategy::sendDataToAll (const shared_ptr< pit::Entry > & pitEntry, const Face & inFace, const Data & data) protected
send data to all matched and qualified faces
A matched face is qualified if it is ad-hoc or it is NOT inFace
Parameters
pitEntry PIT entry
inFace face through which the Data comes from
data the Data packet
Definition at line 209 of file strategy.cpp.
References sendData().
Referenced by afterReceiveData(), and nfd::fw::SelfLearningStrategy::afterReceiveData().
rejectPendingInterest()
void nfd::fw::Strategy::rejectPendingInterest (const shared_ptr< pit::Entry > & pitEntry) inline protected
schedule the PIT entry for immediate deletion
This helper function sets the PIT entry expiry time to zero. The strategy should invoke this function when it concludes that the Interest cannot be forwarded and it does not want to wait for responses from existing upstream nodes.
Definition at line 273 of file strategy.hpp.
References setExpiryTimer().
Referenced by nfd::fw::asf::AsfStrategy::afterReceiveInterest(), nfd::fw::BestRouteStrategyBase::afterReceiveInterest(), nfd::fw::BestRouteStrategy2::afterReceiveInterest(), nfd::fw::MulticastStrategy::afterReceiveInterest(), nfd::fw::NccStrategy::afterReceiveInterest(), nfd::fw::QosStrategy::afterReceiveInterest(), and nfd::fw::SelfLearningStrategy::afterReceiveInterest().
sendNack()
void nfd::fw::Strategy::sendNack (const shared_ptr< pit::Entry > & pitEntry, const Face & outFace, const lp::NackHeader & header) inline protected
send Nack to outFace
Parameters
pitEntry PIT entry
outFace face through which to send out the Nack
header Nack header
The outFace must have a PIT in-record, otherwise this method has no effect.
Definition at line 286 of file strategy.hpp.
Referenced by nfd::fw::BestRouteStrategy2::afterReceiveInterest(), nfd::fw::MulticastStrategy::afterReceiveInterest(), nfd::fw::QosStrategy::afterReceiveInterest(), nfd::fw::SelfLearningStrategy::afterReceiveInterest(), and sendNacks().
sendNacks()
void nfd::fw::Strategy::sendNacks (const shared_ptr< pit::Entry > & pitEntry, const lp::NackHeader & header, std::initializer_list< const Face * > exceptFaces = std::initializer_list<const Face*>()) protected
send Nack to every face that has an in-record, except those in exceptFaces
Parameters
pitEntry PIT entry
header NACK header
exceptFaces list of faces that should be excluded from sending Nacks
Note
This is not an action, but a helper that invokes the sendNack action.
Definition at line 231 of file strategy.cpp.
References sendNack().
Referenced by nfd::fw::SelfLearningStrategy::afterReceiveNack().
setExpiryTimer()
void nfd::fw::Strategy::setExpiryTimer (const shared_ptr< pit::Entry > & pitEntry, time::milliseconds duration) inline protected
Schedule the PIT entry to be erased after duration.
Definition at line 306 of file strategy.hpp.
Referenced by rejectPendingInterest().
lookupFib()
const fib::Entry & nfd::fw::Strategy::lookupFib (const pit::Entry & pitEntry) const protected
performs a FIB lookup, considering Link object if present
Definition at line 253 of file strategy.cpp.
References nfd::Forwarder::getFib(), and nfd::Forwarder::getNetworkRegionTable().
Referenced by nfd::fw::asf::AsfStrategy::afterReceiveInterest(), nfd::fw::BestRouteStrategyBase::afterReceiveInterest(), nfd::fw::BestRouteStrategy2::afterReceiveInterest(), nfd::fw::MulticastStrategy::afterReceiveInterest(), nfd::fw::NccStrategy::afterReceiveInterest(), nfd::fw::QosStrategy::afterReceiveInterest(), nfd::fw::SelfLearningStrategy::afterReceiveInterest(), nfd::fw::SelfLearningStrategy::afterReceiveNack(), and nfd::fw::NccStrategy::doPropagate().
getMeasurements()
MeasurementsAccessor& nfd::fw::Strategy::getMeasurements () inline protected
Definition at line 318 of file strategy.hpp.
Referenced by nfd::fw::NccStrategy::beforeSatisfyInterest(), nfd::fw::NccStrategy::getMeasurementsEntryInfo(), and nfd::fw::NccStrategy::timeoutOnBestFace().
getFace()
Face* nfd::fw::Strategy::getFace (FaceId id) const inline protected
Definition at line 324 of file strategy.hpp.
References nfd::Forwarder::getFace().
Referenced by nfd::fw::NccStrategy::doPropagate().
getFaceTable()
const FaceTable& nfd::fw::Strategy::getFaceTable () const inline protected
Definition at line 330 of file strategy.hpp.
References nfd::Forwarder::getFaceTable().
parseInstanceName()
Strategy::ParsedInstanceName nfd::fw::Strategy::parseInstanceName (const Name & input) static protected
parse a strategy instance name
Parameters
input strategy instance name, may contain version and parameters
Exceptions
std::invalid_argument input format is unacceptable
Definition at line 122 of file strategy.cpp.
Referenced by nfd::fw::asf::AsfStrategy::AsfStrategy(), nfd::fw::BestRouteStrategy::BestRouteStrategy(), nfd::fw::BestRouteStrategy2::BestRouteStrategy2(), nfd::fw::MulticastStrategy::MulticastStrategy(), nfd::fw::NccStrategy::NccStrategy(), nfd::fw::QosStrategy::QosStrategy(), and nfd::fw::SelfLearningStrategy::SelfLearningStrategy().
makeInstanceName()
Name nfd::fw::Strategy::makeInstanceName (const Name & input, const Name & strategyName) static protected
construct a strategy instance name
Parameters
input strategy instance name, may contain version and parameters
strategyName strategy name with version but without parameters; typically this should be getStrategyName()
If input contains a version component, return input unchanged. Otherwise, return input plus the version component taken from strategyName. This allows a strategy instance to be constructed with an unversioned name, but its final instance name should contain the version.
Definition at line 133 of file strategy.cpp.
Referenced by nfd::fw::asf::AsfStrategy::AsfStrategy(), nfd::fw::BestRouteStrategy::BestRouteStrategy(), nfd::fw::BestRouteStrategy2::BestRouteStrategy2(), nfd::fw::MulticastStrategy::MulticastStrategy(), nfd::fw::NccStrategy::NccStrategy(), nfd::fw::QosStrategy::QosStrategy(), and nfd::fw::SelfLearningStrategy::SelfLearningStrategy().
setInstanceName()
void nfd::fw::Strategy::setInstanceName (const Name & name) inline protected
set strategy instance name
Note
This must be called by strategy subclass constructor.
Definition at line 367 of file strategy.hpp.
Referenced by nfd::fw::asf::AsfStrategy::AsfStrategy(), nfd::fw::BestRouteStrategy::BestRouteStrategy(), nfd::fw::BestRouteStrategy2::BestRouteStrategy2(), nfd::fw::MulticastStrategy::MulticastStrategy(), nfd::fw::NccStrategy::NccStrategy(), nfd::fw::QosStrategy::QosStrategy(), and nfd::fw::SelfLearningStrategy::SelfLearningStrategy().
Member Data Documentation
afterAddFace
signal::Signal<FaceTable, Face&>& nfd::fw::Strategy::afterAddFace protected
Definition at line 383 of file strategy.hpp.
beforeRemoveFace
signal::Signal<FaceTable, Face&>& nfd::fw::Strategy::beforeRemoveFace protected
Definition at line 384 of file strategy.hpp.
The documentation for this class was generated from the following files:
ndnSIM/NFD/daemon/fw/strategy.hpp
ndnSIM/NFD/daemon/fw/strategy.cpp