ndnSIM QoS: nfd::fw::RetxSuppressionFixed Class Reference
nfd::fw::RetxSuppressionFixed Class Reference
a retransmission suppression decision algorithm that suppresses retransmissions within a fixed duration
#include <retx-suppression-fixed.hpp>
Public Member Functions
RetxSuppressionFixed (const time::milliseconds &minRetxInterval=DEFAULT_MIN_RETX_INTERVAL)
RetxSuppressionResult decidePerPitEntry (pit::Entry &pitEntry) const
determines whether Interest is a retransmission, and if so, whether it shall be forwarded or suppressed
Static Public Attributes
static const time::milliseconds DEFAULT_MIN_RETX_INTERVAL = 100_ms
Detailed Description
a retransmission suppression decision algorithm that suppresses retransmissions within a fixed duration
Definition at line 38 of file retx-suppression-fixed.hpp.
Constructor & Destructor Documentation
RetxSuppressionFixed()
nfd::fw::RetxSuppressionFixed::RetxSuppressionFixed (const time::milliseconds & minRetxInterval = DEFAULT_MIN_RETX_INTERVAL) explicit
Definition at line 33 of file retx-suppression-fixed.cpp.
Member Function Documentation
decidePerPitEntry()
RetxSuppressionResult nfd::fw::RetxSuppressionFixed::decidePerPitEntry (pit::Entry & pitEntry) const
determines whether Interest is a retransmission, and if so, whether it shall be forwarded or suppressed
Definition at line 40 of file retx-suppression-fixed.cpp.
References nfd::fw::FORWARD, nfd::fw::getLastOutgoing(), nfd::fw::hasPendingOutRecords(), nfd::fw::NEW, and nfd::fw::SUPPRESS.
Referenced by nfd::fw::AccessStrategy::afterReceiveInterest().
Member Data Documentation
DEFAULT_MIN_RETX_INTERVAL
const time::milliseconds nfd::fw::RetxSuppressionFixed::DEFAULT_MIN_RETX_INTERVAL = 100_ms static
Definition at line 51 of file retx-suppression-fixed.hpp.
The documentation for this class was generated from the following files:
ndnSIM/NFD/daemon/fw/retx-suppression-fixed.hpp
ndnSIM/NFD/daemon/fw/retx-suppression-fixed.cpp