ndnSIM QoS: nfd::fw Namespace Reference
nfd::fw Namespace Reference
Namespaces
asf
Classes
class AccessStrategy
Access Router Strategy version 1.
class AdmitAllUnsolicitedDataPolicy
admits all unsolicited Data
class AdmitLocalUnsolicitedDataPolicy
admits unsolicited Data from local faces
class AdmitNetworkUnsolicitedDataPolicy
admits unsolicited Data from non-local faces
class BestRouteStrategy
Best Route strategy version 1.
class BestRouteStrategy2
Best Route strategy version 4.
class BestRouteStrategyBase
class DropAllUnsolicitedDataPolicy
drops all unsolicited Data
class MulticastStrategy
a forwarding strategy that forwards Interest to all FIB nexthops
class NccStrategy
a forwarding strategy similar to CCNx 0.7.2
class NdnPriorityTxQueue
Class defines priority queue.
class ProcessNackTraits
class ProcessNackTraitsBase
provides a common procedure for processing Nacks
class QosQueue
Class that implements QoS queue for NDN packets.
class QosStrategy
A forwarding strategy that uses WFQ to forward packets based on priority to enable QoS.
struct QueueItem
Defines queue item for use qos queues.
class RetxSuppressionExponential
a retransmission suppression decision algorithm that suppresses retransmissions using exponential backoff
class RetxSuppressionFixed
a retransmission suppression decision algorithm that suppresses retransmissions within a fixed duration
class SelfLearningStrategy
Self-learning strategy.
class Strategy
represents a forwarding strategy
class StrategyInfo
contains arbitrary information forwarding strategy places on table entries
struct TBRef
Links application layer to strategy layer for the token bucket.
class TokenBucket
Defines token bucket for use in QoS-strategy.
class UnsolicitedDataPolicy
determines how to process an unsolicited Data
Typedefs
typedef DropAllUnsolicitedDataPolicy DefaultUnsolicitedDataPolicy
the default UnsolicitedDataPolicy
Enumerations
enum DuplicateNonceWhere {
DUPLICATE_NONCE_NONE = 0, DUPLICATE_NONCE_IN_SAME = (1 << 0), DUPLICATE_NONCE_IN_OTHER = (1 << 1), DUPLICATE_NONCE_OUT_SAME = (1 << 2),
DUPLICATE_NONCE_OUT_OTHER = (1 << 3)
}
indicates where duplicate Nonces are found
enum QosPacketType { INVALID = -1, INTEREST = 0, DATA, NACK }
Enumerator used to describe packet type.
enum PacketType { PacketType::INTEREST = 0, PacketType::DATA, PacketType::NACK }
Enumerator used to indicate packet type.
enum RetxSuppressionResult { RetxSuppressionResult::NEW, RetxSuppressionResult::FORWARD, RetxSuppressionResult::SUPPRESS }
enum UnsolicitedDataDecision { UnsolicitedDataDecision::DROP, UnsolicitedDataDecision::CACHE }
a decision made by UnsolicitedDataPolicy
Functions
NFD_REGISTER_STRATEGY (AccessStrategy)
bool wouldViolateScope (const Face &inFace, const Interest &interest, const Face &outFace)
determine whether forwarding the Interest in pitEntry to outFace would violate scope
bool canForwardToLegacy (const pit::Entry &pitEntry, const Face &face)
decide whether Interest can be forwarded to face
int findDuplicateNonce (const pit::Entry &pitEntry, uint32_t nonce, const Face &face)
determine whether pitEntry has duplicate Nonce nonce
bool hasPendingOutRecords (const pit::Entry &pitEntry)
determine whether pitEntry has any pending out-records
time::steady_clock::TimePoint getLastOutgoing (const pit::Entry &pitEntry)
NFD_REGISTER_STRATEGY (BestRouteStrategy)
NFD_REGISTER_STRATEGY (BestRouteStrategy2)
static bool isNextHopEligible (const Face &inFace, const Interest &interest, const fib::NextHop &nexthop, const shared_ptr< pit::Entry > &pitEntry, bool wantUnused=false, time::steady_clock::TimePoint now=time::steady_clock::TimePoint::min())
determines whether a NextHop is eligible
static fib::NextHopList::const_iterator findEligibleNextHopWithEarliestOutRecord (const Face &inFace, const Interest &interest, const fib::NextHopList &nexthops, const shared_ptr< pit::Entry > &pitEntry)
pick an eligible NextHop with earliest out-record
NFD_REGISTER_STRATEGY (MulticastStrategy)
NFD_REGISTER_STRATEGY (NccStrategy)
NFD_REGISTER_STRATEGY (QosStrategy)
static bool isNextHopEligible (const Face &inFace, const Interest &interest, const fib::NextHop &nexthop, const shared_ptr< pit::Entry > &pitEntry, bool wantUnused=false, time::steady_clock::TimePoint now=time::steady_clock::TimePoint::min())
static fib::NextHopList::const_iterator findEligibleNextHopWithEarliestOutRecord (const Face &inFace, const Interest &interest, const fib::NextHopList &nexthops, const shared_ptr< pit::Entry > &pitEntry)
Pick an eligible NextHop with earliest out-record.
NFD_REGISTER_STRATEGY (SelfLearningStrategy)
std::ostream & operator<< (std::ostream &os, UnsolicitedDataDecision d)
Variables
TBRef CT
AccessStrategy
BestRouteStrategy2
MulticastStrategy
ProcessNackTraits
QosStrategy
SelfLearningStrategy
Strategy
DropAllUnsolicitedDataPolicy
AdmitLocalUnsolicitedDataPolicy
AdmitNetworkUnsolicitedDataPolicy
AdmitAllUnsolicitedDataPolicy
Typedef Documentation
DefaultUnsolicitedDataPolicy
typedef DropAllUnsolicitedDataPolicy nfd::fw::DefaultUnsolicitedDataPolicy
the default UnsolicitedDataPolicy
Definition at line 138 of file unsolicited-data-policy.hpp.
Enumeration Type Documentation
DuplicateNonceWhere
enum nfd::fw::DuplicateNonceWhere
indicates where duplicate Nonces are found
Enumerator
DUPLICATE_NONCE_NONE
no duplicate Nonce is found
DUPLICATE_NONCE_IN_SAME
in-record of same face
DUPLICATE_NONCE_IN_OTHER
in-record of other face
DUPLICATE_NONCE_OUT_SAME
out-record of same face
DUPLICATE_NONCE_OUT_OTHER
out-record of other face
Definition at line 59 of file algorithm.hpp.
QosPacketType
enum nfd::fw::QosPacketType
Enumerator used to describe packet type.
Enumerator
INVALID
INTEREST
DATA
NACK
Definition at line 44 of file ndn-qos-queue.hpp.
PacketType
enum nfd::fw::PacketType strong
Enumerator used to indicate packet type.
Enumerator
INTEREST
DATA
NACK
Definition at line 43 of file qos-strategy.hpp.
RetxSuppressionResult
enum nfd::fw::RetxSuppressionResult strong
Enumerator
NEW
Interest is new (not a retransmission)
FORWARD
Interest is retransmission and should be forwarded.
SUPPRESS
Interest is retransmission and should be suppressed.
Definition at line 34 of file retx-suppression.hpp.
UnsolicitedDataDecision
enum nfd::fw::UnsolicitedDataDecision strong
a decision made by UnsolicitedDataPolicy
Enumerator
DROP
the Data should be dropped
CACHE
the Data should be cached in the ContentStore
Definition at line 36 of file unsolicited-data-policy.hpp.
Function Documentation
NFD_REGISTER_STRATEGY() [1/7]
nfd::fw::NFD_REGISTER_STRATEGY (AccessStrategy)
wouldViolateScope()
bool nfd::fw::wouldViolateScope (const Face & inFace, const Interest & interest, const Face & outFace)
determine whether forwarding the Interest in pitEntry to outFace would violate scope
See also
https://redmine.named-data.net/projects/nfd/wiki/ScopeControl
Definition at line 32 of file algorithm.cpp.
Referenced by nfd::fw::BestRouteStrategyBase::afterReceiveInterest(), nfd::fw::MulticastStrategy::afterReceiveInterest(), nfd::fw::NccStrategy::afterReceiveInterest(), nfd::fw::QosStrategy::afterReceiveInterest(), nfd::fw::NccStrategy::doPropagate(), nfd::fw::asf::ProbingModule::getFaceToProbe(), and isNextHopEligible().
canForwardToLegacy()
bool nfd::fw::canForwardToLegacy (const pit::Entry & pitEntry, const Face & face)
decide whether Interest can be forwarded to face
Returns
true if out-record of this face does not exist or has expired, and there is an in-record not of this face
Note
This algorithm has a weakness that it does not permit consumer retransmissions before out-record expires. Therefore, it's not recommended to use this function in new strategies.
Definition at line 54 of file algorithm.cpp.
Referenced by nfd::fw::BestRouteStrategyBase::afterReceiveInterest(), nfd::fw::NccStrategy::afterReceiveInterest(), and nfd::fw::NccStrategy::doPropagate().
findDuplicateNonce()
int nfd::fw::findDuplicateNonce (const pit::Entry & pitEntry, uint32_t nonce, const Face & face)
determine whether pitEntry has duplicate Nonce nonce
Returns
OR'ed DuplicateNonceWhere
Definition at line 78 of file algorithm.cpp.
References DUPLICATE_NONCE_IN_OTHER, DUPLICATE_NONCE_IN_SAME, DUPLICATE_NONCE_NONE, DUPLICATE_NONCE_OUT_OTHER, and DUPLICATE_NONCE_OUT_SAME.
hasPendingOutRecords()
bool nfd::fw::hasPendingOutRecords (const pit::Entry & pitEntry)
determine whether pitEntry has any pending out-records
Returns
true if there is at least one out-record waiting for Data
Definition at line 108 of file algorithm.cpp.
Referenced by nfd::fw::BestRouteStrategyBase::afterReceiveInterest(), nfd::fw::NccStrategy::afterReceiveInterest(), nfd::fw::RetxSuppressionExponential::decidePerPitEntry(), and nfd::fw::RetxSuppressionFixed::decidePerPitEntry().
getLastOutgoing()
time::steady_clock::TimePoint nfd::fw::getLastOutgoing (const pit::Entry & pitEntry)
Returns
last out-record time
Precondition
pitEntry has one or more unexpired out-records
Definition at line 119 of file algorithm.cpp.
Referenced by nfd::fw::RetxSuppressionExponential::decidePerPitEntry(), and nfd::fw::RetxSuppressionFixed::decidePerPitEntry().
NFD_REGISTER_STRATEGY() [2/7]
nfd::fw::NFD_REGISTER_STRATEGY (BestRouteStrategy)
NFD_REGISTER_STRATEGY() [3/7]
nfd::fw::NFD_REGISTER_STRATEGY (BestRouteStrategy2)
isNextHopEligible() [1/2]
static bool nfd::fw::isNextHopEligible (const Face & inFace, const Interest & interest, const fib::NextHop & nexthop, const shared_ptr< pit::Entry > & pitEntry, bool wantUnused = false, time::steady_clock::TimePoint now = time::steady_clock::TimePoint::min()) static
determines whether a NextHop is eligible
Parameters
inFace incoming face of current Interest
interest incoming Interest
nexthop next hop
pitEntry PIT entry
wantUnused if true, NextHop must not have unexpired out-record
now time::steady_clock::now(), ignored if !wantUnused
Definition at line 76 of file best-route-strategy2.cpp.
References wouldViolateScope().
Referenced by findEligibleNextHopWithEarliestOutRecord().
findEligibleNextHopWithEarliestOutRecord() [1/2]
static fib::NextHopList::const_iterator nfd::fw::findEligibleNextHopWithEarliestOutRecord (const Face & inFace, const Interest & interest, const fib::NextHopList & nexthops, const shared_ptr< pit::Entry > & pitEntry) static
pick an eligible NextHop with earliest out-record
Note
It is assumed that every nexthop has an out-record.
Definition at line 107 of file best-route-strategy2.cpp.
References isNextHopEligible().
Referenced by nfd::fw::BestRouteStrategy2::afterReceiveInterest(), and nfd::fw::QosStrategy::afterReceiveInterest().
NFD_REGISTER_STRATEGY() [4/7]
nfd::fw::NFD_REGISTER_STRATEGY (MulticastStrategy)
NFD_REGISTER_STRATEGY() [5/7]
nfd::fw::NFD_REGISTER_STRATEGY (NccStrategy)
NFD_REGISTER_STRATEGY() [6/7]
nfd::fw::NFD_REGISTER_STRATEGY (QosStrategy)
isNextHopEligible() [2/2]
static bool nfd::fw::isNextHopEligible (const Face & inFace, const Interest & interest, const fib::NextHop & nexthop, const shared_ptr< pit::Entry > & pitEntry, bool wantUnused = false, time::steady_clock::TimePoint now = time::steady_clock::TimePoint::min()) static
Definition at line 88 of file qos-strategy.cpp.
References wouldViolateScope().
findEligibleNextHopWithEarliestOutRecord() [2/2]
static fib::NextHopList::const_iterator nfd::fw::findEligibleNextHopWithEarliestOutRecord (const Face & inFace, const Interest & interest, const fib::NextHopList & nexthops, const shared_ptr< pit::Entry > & pitEntry) static
Pick an eligible NextHop with earliest out-record.
Note
It is assumed that every nexthop has an out-record.
Definition at line 119 of file qos-strategy.cpp.
References isNextHopEligible().
NFD_REGISTER_STRATEGY() [7/7]
nfd::fw::NFD_REGISTER_STRATEGY (SelfLearningStrategy)
operator<<()
std::ostream & nfd::fw::operator<< (std::ostream & os, UnsolicitedDataDecision d)
Definition at line 33 of file unsolicited-data-policy.cpp.
References CACHE, and DROP.
Variable Documentation
CT
TBRef nfd::fw::CT
Definition at line 28 of file TBucketRef.cpp.
Referenced by nfd::fw::QosStrategy::prioritySend(), nfd::fw::QosStrategy::QosStrategy(), and ns3::ndn::TBDriver::UpdateBucket().
AccessStrategy
nfd::fw::AccessStrategy
Definition at line 33 of file access-strategy.cpp.
BestRouteStrategy2
nfd::fw::BestRouteStrategy2
Definition at line 36 of file best-route-strategy2.cpp.
MulticastStrategy
nfd::fw::MulticastStrategy
Definition at line 35 of file multicast-strategy.cpp.
ProcessNackTraits
nfd::fw::ProcessNackTraits
Definition at line 32 of file process-nack-traits.cpp.
QosStrategy
nfd::fw::QosStrategy
Definition at line 37 of file qos-strategy.cpp.
SelfLearningStrategy
nfd::fw::SelfLearningStrategy
Definition at line 42 of file self-learning-strategy.cpp.
Strategy
nfd::fw::Strategy
Definition at line 37 of file strategy.cpp.
DropAllUnsolicitedDataPolicy
nfd::fw::DropAllUnsolicitedDataPolicy
Definition at line 70 of file unsolicited-data-policy.cpp.
AdmitLocalUnsolicitedDataPolicy
nfd::fw::AdmitLocalUnsolicitedDataPolicy
Definition at line 79 of file unsolicited-data-policy.cpp.
AdmitNetworkUnsolicitedDataPolicy
nfd::fw::AdmitNetworkUnsolicitedDataPolicy
Definition at line 91 of file unsolicited-data-policy.cpp.
AdmitAllUnsolicitedDataPolicy
nfd::fw::AdmitAllUnsolicitedDataPolicy
Definition at line 103 of file unsolicited-data-policy.cpp.